Switch to using only space to indent
The old style apparently isn't supported by some editors and proved a
repeated pain point with GSoC contributors.

A small number of files which are imported from elsewhere are left
with whatever indentation style the original uses in case we want
to update them.

Fixes #787, reported by Germán M. Bravo.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -50,17 +50,17 @@ check_checksum() {
 
   if [ -z "$SHA256SUM_TOOL" ] ; then
     for SHA256SUM_TOOL in \
-	'${SHA256SUM-sha256sum} 2>/dev/null|cut -d\  -f1' \
-	'${SHASUM-shasum} -a256 2>/dev/null|cut -d\  -f1' \
-	'${OPENSSL-openssl} sha256 2>/dev/null|sed "s/.* //"' \
-	'' ; do
+        '${SHA256SUM-sha256sum} 2>/dev/null|cut -d\  -f1' \
+        '${SHASUM-shasum} -a256 2>/dev/null|cut -d\  -f1' \
+        '${OPENSSL-openssl} sha256 2>/dev/null|sed "s/.* //"' \
+        '' ; do
       if [ -z "$SHA256SUM_TOOL" ] ; then
-	cat <<'END'
+        cat <<'END'
 Need sha256sum or shasum or openssl installed to check SHA256 checksums.
 Set environment variable SHA256SUM, SHASUM or OPENSSL if the tool isn't on
 your PATH.
 END
-	exit 1
+        exit 1
       fi
       # Sanity check by hashing empty input.
       r=`:|eval "$SHA256SUM_TOOL"`
@@ -92,8 +92,8 @@ check_at_least() {
     shift
     if [ "$1" != "$v" ] ; then
       if [ -z "$1" ] || [ "$1" -lt "$v" ] ; then
-	IFS=$save_IFS
-	return 1
+        IFS=$save_IFS
+        return 1
       fi
       break
     fi
@@ -116,30 +116,30 @@ need_to_build() {
       ;;
     *)
       if [ -n "$binary" ] ; then
-	if [ -s "../patches/$package/series" ] ; then
-	  echo "There are patches to apply to $package so using private build"
-	else
-	  # Check if a new enough version is already installed.
-	  version_installed=`"$binary" --version 2>/dev/null|sed '1,1 s/.* //p;d'`
-	  if [ -n "$version_installed" ] ; then
-	    # Fast track equality.
-	    if [ "$version_installed" = "$version" ] ; then
-	      echo "$binary $version_installed installed, exactly what's needed"
-	      return 1
-	    fi
-	    # Deal with Debian libtool package unhelpfully reporting this:
-	    # libtool (GNU libtool) 2.4.7 Debian-2.5.4-3
-	    # This seems to actually be upstream 2.5.4.
-	    case $version_installed in
-	      Debian-*)
-		version_installed=`echo "$version_installed"|sed 's/Debian-//;s/-.*//'` ;;
-	    esac
-	    if check_at_least "$version_installed" "$version" ; then
-	      echo "$binary $version_installed installed >= $version required"
-	      return 1
-	    fi
-	  fi
-	fi
+        if [ -s "../patches/$package/series" ] ; then
+          echo "There are patches to apply to $package so using private build"
+        else
+          # Check if a new enough version is already installed.
+          version_installed=`"$binary" --version 2>/dev/null|sed '1,1 s/.* //p;d'`
+          if [ -n "$version_installed" ] ; then
+            # Fast track equality.
+            if [ "$version_installed" = "$version" ] ; then
+              echo "$binary $version_installed installed, exactly what's needed"
+              return 1
+            fi
+            # Deal with Debian libtool package unhelpfully reporting this:
+            # libtool (GNU libtool) 2.4.7 Debian-2.5.4-3
+            # This seems to actually be upstream 2.5.4.
+            case $version_installed in
+              Debian-*)
+                version_installed=`echo "$version_installed"|sed 's/Debian-//;s/-.*//'` ;;
+            esac
+            if check_at_least "$version_installed" "$version" ; then
+              echo "$binary $version_installed installed >= $version required"
+              return 1
+            fi
+          fi
+        fi
       fi
       ;;
   esac
@@ -156,9 +156,9 @@ lazy_build() {
   if [ "$ext" = "tar.xz" ] ; then
     if [ -z "$xz_ok" ] ; then
       if ${XZ-xz} --version > /dev/null 2>&1 ; then
-	xz_ok=1
+        xz_ok=1
       else
-	xz_ok=0
+        xz_ok=0
       fi
     fi
     if [ "$xz_ok" = 0 ] ; then
@@ -172,9 +172,9 @@ lazy_build() {
       # bzip2 --version doesn't exit with code 0 in upstream version (though
       # Debian at least patch this bug), so use --help to check it.
       if bzip2 --help > /dev/null 2>&1 ; then
-	bz2_ok=1
+        bz2_ok=1
       else
-	bz2_ok=0
+        bz2_ok=0
       fi
     fi
     if [ "$bz2_ok" = 0 ] ; then
@@ -204,8 +204,8 @@ lazy_build() {
       # Canonicalise main_worktree_dir before comparing with pwd.
       main_worktree_dir=`cd "$main_worktree_dir" && pwd`
       if [ "$main_worktree_dir/BUILD" != "`pwd`" ] ; then
-	# If main_tarball is set non-empty, then we're a linked worktree.
-	main_tarball=$main_worktree_dir/BUILD/$tarball
+        # If main_tarball is set non-empty, then we're a linked worktree.
+        main_tarball=$main_worktree_dir/BUILD/$tarball
       fi
     fi
     if [ -n "$main_tarball" ] && [ -f "$main_tarball" ] ; then
@@ -213,49 +213,49 @@ lazy_build() {
       tarball=$main_tarball
     else
       if [ -z "$FETCH_URL_TOOL" ] ; then
-	if ${WGET-wget} --version > /dev/null 2>&1 ; then
-	  FETCH_URL_TOOL="${WGET-wget} -O-"
-	elif ${CURL-curl} --version > /dev/null 2>&1 || [ "$?" = 2 ] ; then
-	  # curl --version exits with code 2 (~7.18.2) or 0 (7.35.0).
-	  # -L is needed to follow HTTP redirects.
-	  FETCH_URL_TOOL="${CURL-curl} -L"
-	elif ${LWP_REQUEST-lwp-request} -v > /dev/null 2>&1 || [ "$?" = 9 ] || [ "$?" = 255 ] ; then
-	  # lwp-request -v exits with code 9 (5.810) or 255 (6.03)
-	  FETCH_URL_TOOL="${LWP_REQUEST-lwp-request} -mGET"
-	else
-	  cat <<END >&2
+        if ${WGET-wget} --version > /dev/null 2>&1 ; then
+          FETCH_URL_TOOL="${WGET-wget} -O-"
+        elif ${CURL-curl} --version > /dev/null 2>&1 || [ "$?" = 2 ] ; then
+          # curl --version exits with code 2 (~7.18.2) or 0 (7.35.0).
+          # -L is needed to follow HTTP redirects.
+          FETCH_URL_TOOL="${CURL-curl} -L"
+        elif ${LWP_REQUEST-lwp-request} -v > /dev/null 2>&1 || [ "$?" = 9 ] || [ "$?" = 255 ] ; then
+          # lwp-request -v exits with code 9 (5.810) or 255 (6.03)
+          FETCH_URL_TOOL="${LWP_REQUEST-lwp-request} -mGET"
+        else
+          cat <<END >&2
 Neither wget nor curl nor lwp-request found - install one of them or if already
 installed, set WGET, CURL or LWP_REQUEST to the full path.  Alternatively,
 download $url
 to directory `pwd`
 then rerun this script.
 END
-	  exit 1
-	fi
+          exit 1
+        fi
       fi
       url="https://github.com/xapian/xapian-dev-deps/releases/download/current/$tarball"
       case $basename in
       file-*)
-	case $download_protocol in
-	  ftp) url="ftp://ftp.astron.com/pub/file/$tarball" ;;
-	  # We used to use http://fossies.org/ but that now redirects to https.
-	esac ;;
+        case $download_protocol in
+          ftp) url="ftp://ftp.astron.com/pub/file/$tarball" ;;
+          # We used to use http://fossies.org/ but that now redirects to https.
+        esac ;;
       *[13579][a-z])
-	# GNU alpha release
-	case $download_protocol in
-	  ftp) url="ftp://alpha.gnu.org/gnu/$package/$tarball" ;;
-	  http) url="http://alpha.gnu.org/gnu/$package/$tarball" ;;
-	esac ;;
+        # GNU alpha release
+        case $download_protocol in
+          ftp) url="ftp://alpha.gnu.org/gnu/$package/$tarball" ;;
+          http) url="http://alpha.gnu.org/gnu/$package/$tarball" ;;
+        esac ;;
       *)
-	case $download_protocol in
-	  ftp) url="ftp://ftp.gnu.org/gnu/$package/$tarball" ;;
-	  http) url="http://ftpmirror.gnu.org/$package/$tarball" ;;
-	esac ;;
+        case $download_protocol in
+          ftp) url="ftp://ftp.gnu.org/gnu/$package/$tarball" ;;
+          http) url="http://ftpmirror.gnu.org/$package/$tarball" ;;
+        esac ;;
       esac
       case $download_protocol,$url in
-	http,https:*)
-	  echo "warning: No http: link for $tarball available, using https:"
-	  ;;
+        http,https:*)
+          echo "warning: No http: link for $tarball available, using https:"
+          ;;
       esac
 
       # Keep the tarball under a quarantined name until we've verified its
@@ -263,7 +263,7 @@ END
       # the tarball in the main worktree's BUILD directory so that it can
       # be shared with other worktrees.
       if [ -n "$main_tarball" ] ; then
-	tarball=$main_tarball
+        tarball=$main_tarball
       fi
       quarantined_tarball=$tarball-quarantine.$$
       rm -f "$quarantined_tarball"
@@ -297,16 +297,16 @@ END
     case $tarball in
       */*) ;; # Only expire tarballs from the main worktree.
       *)
-	case `git worktree list --porcelain 2>/dev/null|grep -c '^worktree '` in
-	  1|0)
-	    # Remove tarballs of other versions if there's only one worktree, or if
-	    # using git < 2.5 (before worktrees were added).
-	    for f in "$package"-* ; do
-	      [ "$f" = "$tarball" ] || rm -rf "$f"
-	    done
-	    ;;
-	esac
-	;;
+        case `git worktree list --porcelain 2>/dev/null|grep -c '^worktree '` in
+          1|0)
+            # Remove tarballs of other versions if there's only one worktree, or if
+            # using git < 2.5 (before worktrees were added).
+            for f in "$package"-* ; do
+              [ "$f" = "$tarball" ] || rm -rf "$f"
+            done
+            ;;
+        esac
+        ;;
     esac
 
     case $ext in
@@ -331,9 +331,9 @@ END
     if [ -s "$series" ] ; then
       echo "Applying patches from $package/series"
       sed -n 's/['"$tab"' ]*\(#.*\)\?$//;/./p' "$series" | \
-	  while read p ; do
-	echo "Applying patch $package/$p"
-	patch -p1 < "../../patches/$package/$p" || exit $?
+          while read p ; do
+        echo "Applying patch $package/$p"
+        patch -p1 < "../../patches/$package/$p" || exit $?
       done
     fi
 
@@ -737,11 +737,11 @@ for module in ${@:-xapian-core xapian-applications/omega swig xapian-bindings} ;
       var=`echo "$d"|sed 's!.*[-/]!!g'`_common_commit_hash
       hash=`eval echo \\\$"$var"`
       if [ -f "$gitdir/shallow" ] ; then
-	if git reflog "$hash" -- 2> /dev/null ; then
-	  : # Already have the desired commit.
-	else
-	  git fetch --unshallow
-	fi
+        if git reflog "$hash" -- 2> /dev/null ; then
+          : # Already have the desired commit.
+        else
+          git fetch --unshallow
+        fi
       fi
       handle_git_external "$d/.common.git" "$hash" "$xapian_common_clone_url"
       ln -sf .common.git/xapian-core/common "$d/common"
@@ -893,49 +893,49 @@ for d in $modules ; do
     swig)
       case "$*" in
       *--host=*|*--host" "*)
-	# We're cross-building, but SWIG needs to be built natively.
-	swig_configure_args=
-	skip=
-	for arg in "$@" ; do
-	  if [ -n "$skip" ] ; then
-	    skip=
-	    continue
-	  fi
-	  case $arg in
-	  --host=*)
-	    # Drop --host=xxx
-	    continue ;;
-	  --host)
-	    # Drop --host xxx
-	    skip=1
-	    continue ;;
-	  CC=*|CXX=*)
-	    # Drop CC=xxx or CXX=xxx
-	    continue ;;
-	  CC_FOR_BUILD=*|CXX_FOR_BUILD=*)
-	    # CC_FOR_BUILD=xxx -> CC=xxx; CXX_FOR_BUILD=xxx -> CXX=xxx
-	    arg=`echo "$arg"|sed 's/_FOR_BUILD//'`
-	    ;;
-	  SWIG=*)
-	    # Drop SWIG=xxx - not useful and could cause problems.
-	    continue ;;
-	  esac
-	  swig_configure_args="$swig_configure_args "\'`printf '%s' "$arg"|sed "s/'/'\\\\\\\\''/g"`\'
-	done
-	# Also handle compilers specified in environment variables.  We can
-	# just reassign them unconditionally as CC and CXX are ignored if
-	# empty.
-	(
-	  CC=$CC_FOR_BUILD
-	  CXX=$CC_FOR_BUILD
-	  export CC
-	  export CXX
-	  cd "$d" && eval "$configure" $swig_configure_args
-	)
-	;;
+        # We're cross-building, but SWIG needs to be built natively.
+        swig_configure_args=
+        skip=
+        for arg in "$@" ; do
+          if [ -n "$skip" ] ; then
+            skip=
+            continue
+          fi
+          case $arg in
+          --host=*)
+            # Drop --host=xxx
+            continue ;;
+          --host)
+            # Drop --host xxx
+            skip=1
+            continue ;;
+          CC=*|CXX=*)
+            # Drop CC=xxx or CXX=xxx
+            continue ;;
+          CC_FOR_BUILD=*|CXX_FOR_BUILD=*)
+            # CC_FOR_BUILD=xxx -> CC=xxx; CXX_FOR_BUILD=xxx -> CXX=xxx
+            arg=`echo "$arg"|sed 's/_FOR_BUILD//'`
+            ;;
+          SWIG=*)
+            # Drop SWIG=xxx - not useful and could cause problems.
+            continue ;;
+          esac
+          swig_configure_args="$swig_configure_args "\'`printf '%s' "$arg"|sed "s/'/'\\\\\\\\''/g"`\'
+        done
+        # Also handle compilers specified in environment variables.  We can
+        # just reassign them unconditionally as CC and CXX are ignored if
+        # empty.
+        (
+          CC=$CC_FOR_BUILD
+          CXX=$CC_FOR_BUILD
+          export CC
+          export CXX
+          cd "$d" && eval "$configure" $swig_configure_args
+        )
+        ;;
       *)
-	cd "$d" && "$configure" ${1+"$@"}
-	;;
+        cd "$d" && "$configure" ${1+"$@"}
+        ;;
       esac
       ;;
     xapian-core)
diff --git a/xapian-core/xapian-config.in b/xapian-core/xapian-config.in
--- a/xapian-core/xapian-config.in
+++ b/xapian-core/xapian-config.in
@@ -56,8 +56,8 @@ is_uninstalled_cache=
 is_uninstalled()
 {
     if [ -z "$is_uninstalled_cache" ]; then
-	[ -n "$builddir" -a -f "${builddir}Makefile" ]
-	is_uninstalled_cache=$?
+        [ -n "$builddir" -a -f "${builddir}Makefile" ]
+        is_uninstalled_cache=$?
     fi
     return $is_uninstalled_cache
 }
@@ -82,9 +82,9 @@ need_explicit_dependencies()
 
     # If the .la file hasn't been installed, assume there are shared libraries.
     if [ -f "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la" ] ; then
-	# If "$dlname" is empty, we only have static libraries.
-	extract_dlname "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la"
-	[ -n "$dlname" ] || return 0 # "true"
+        # If "$dlname" is empty, we only have static libraries.
+        extract_dlname "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la"
+        [ -n "$dlname" ] || return 0 # "true"
     fi
 
     # Vanilla libtool set this to either "yes" or "unknown" and then handles
@@ -104,20 +104,20 @@ set_L_to_library_path() {
 set_I() {
     ##UNINSTONLYBEGIN
     if is_uninstalled ; then
-	set_I_for_uninstalled
+        set_I_for_uninstalled
     else
     ##UNINSTONLYEND
-	# Adding -I/usr/include to CXXFLAGS causes problems with certain
-	# versions of GCC on some platforms where GCC generates "fixed"
-	# versions of vendor supplied include headers at install time.
-	# Normally these are used instead of those in /usr/include, but if
-	# you explicitly pass -I/usr/include you get the non-fixed
-	# versions.  More recent GCC versions simply ignore -I/usr/include
-	# but we want to support older versions too.
-	case "@incdir@" in
-	/usr/include|/usr/include/c++) I= ;;
-	*) I="-I@incdir@" ;;
-	esac
+        # Adding -I/usr/include to CXXFLAGS causes problems with certain
+        # versions of GCC on some platforms where GCC generates "fixed"
+        # versions of vendor supplied include headers at install time.
+        # Normally these are used instead of those in /usr/include, but if
+        # you explicitly pass -I/usr/include you get the non-fixed
+        # versions.  More recent GCC versions simply ignore -I/usr/include
+        # but we want to support older versions too.
+        case "@incdir@" in
+        /usr/include|/usr/include/c++) I= ;;
+        *) I="-I@incdir@" ;;
+        esac
     ##UNINSTONLYBEGIN
     fi
     ##UNINSTONLYEND
@@ -126,10 +126,10 @@ set_I() {
 set_I_swig() {
     ##UNINSTONLYBEGIN
     if is_uninstalled ; then
-	set_I_for_uninstalled
+        set_I_for_uninstalled
     else
     ##UNINSTONLYEND
-	I="-I@incdir@"
+        I="-I@incdir@"
     ##UNINSTONLYBEGIN
     fi
     ##UNINSTONLYEND
@@ -163,24 +163,24 @@ extract_dependency_libs_() {
     eval "$assignment"
     dependency_libs=`echo " $dependency_libs "|sed "s/$mws/ /g"`
     while true ; do
-	file=`echo "$dependency_libs"|sed "s,$pat"',\2\3\4.la,'`
-	case $file in
-	*.la)
-	    # Replace "/path/to/libfoo.la" with "-L/path/to -lfoo".
-	    deps="$deps "`echo "$dependency_libs"|sed "s,$pat"',\1-L\2 -l\4,'`
-	    # Put the trailing part in $1 which is a local variable.
-	    set "`echo "$dependency_libs"|sed "s,$pat"',\5,'`"
-	    # And expand any dependency libs from libfoo.la.
-	    extract_dependency_libs_ "$file"
-	    # Set dependency_libs to the trailing part, ready for the
-	    # next pass of the loop which checks for more .la files.
-	    dependency_libs=$1
-	    ;;
-	*)
-	    deps=$deps$dependency_libs
-	    break
-	    ;;
-	esac
+        file=`echo "$dependency_libs"|sed "s,$pat"',\2\3\4.la,'`
+        case $file in
+        *.la)
+            # Replace "/path/to/libfoo.la" with "-L/path/to -lfoo".
+            deps="$deps "`echo "$dependency_libs"|sed "s,$pat"',\1-L\2 -l\4,'`
+            # Put the trailing part in $1 which is a local variable.
+            set "`echo "$dependency_libs"|sed "s,$pat"',\5,'`"
+            # And expand any dependency libs from libfoo.la.
+            extract_dependency_libs_ "$file"
+            # Set dependency_libs to the trailing part, ready for the
+            # next pass of the loop which checks for more .la files.
+            dependency_libs=$1
+            ;;
+        *)
+            deps=$deps$dependency_libs
+            break
+            ;;
+        esac
     done
 }
 
@@ -194,118 +194,118 @@ while [ 0 != "$#" ] ; do
     shift
     case $arg in
     --help)
-	echo "$PROG_NAME - $PROG_DESC"
-	echo
-	show_usage 0
-	;;
+        echo "$PROG_NAME - $PROG_DESC"
+        echo
+        show_usage 0
+        ;;
 
     --version)
-	echo "$PROG_NAME - @PACKAGE_STRING@"
-	exit 0
-	;;
+        echo "$PROG_NAME - @PACKAGE_STRING@"
+        exit 0
+        ;;
 
     --cxxflags|--swigflags|--libs|--ltlibs)
-	actions="$actions $arg"
-	;;
+        actions="$actions $arg"
+        ;;
 
     --static)
-	static=yes
-	;;
+        static=yes
+        ;;
 
     --from-xo-lib-xapian)
-	# Top Secret option which allows us to give a more helpful error
-	# message if we're asked to link with an uninstalled libxapian@LIBRARY_VERSION_SUFFIX@
-	# and libtool isn't in use.
-	xo_lib_xapian=yes
-	;;
+        # Top Secret option which allows us to give a more helpful error
+        # message if we're asked to link with an uninstalled libxapian@LIBRARY_VERSION_SUFFIX@
+        # and libtool isn't in use.
+        xo_lib_xapian=yes
+        ;;
 
     -*)
-	echo "$0: Unrecognized option: $arg" 1>&2
-	show_usage 1 1>&2
-	;;
+        echo "$0: Unrecognized option: $arg" 1>&2
+        show_usage 1 1>&2
+        ;;
 
     *)
-	show_usage 1 1>&2
-	;;
+        show_usage 1 1>&2
+        ;;
     esac
 done
 
 for arg in $actions ; do
     case $arg in
     --cxxflags)
-	set_I
-	F=
-	[ -n "@abi_affecting_cxxflags@" ] && F="@abi_affecting_cxxflags@ "
-	echo "$I$F"
-	;;
+        set_I
+        F=
+        [ -n "@abi_affecting_cxxflags@" ] && F="@abi_affecting_cxxflags@ "
+        echo "$I$F"
+        ;;
 
     --swigflags)
-	set_I_swig
-	echo "$I"
-	;;
+        set_I_swig
+        echo "$I"
+        ;;
 
     --libs)
-	##UNINSTONLYBEGIN
-	if is_uninstalled ; then
-	    if [ no = "$xo_lib_xapian" ]; then
-		echo "$0: Use libtool and '$PROG_NAME --ltlibs'" 1>&2
-	    else
-		configure_ac='configure.in (or configure.ac)'
-		# If ac_top_srcdir isn't passed to us, we just end up looking
-		# in the current directory, which is a sensible fallback.
-		if [ -r "${ac_top_srcdir}configure.ac" ]; then
-		    configure_ac=configure.ac
-		elif [ -r "${ac_top_srcdir}configure.in" ]; then
-		    configure_ac=configure.in
-		fi
-		echo "$0: Add AC_PROG_LIBTOOL to your $configure_ac" 1>&2
-	    fi
-	    echo "to link with an uninstalled libxapian@LIBRARY_VERSION_SUFFIX@." 1>&2
-	    exit 1
-	fi
-	##UNINSTONLYEND
-	set_L_to_library_path
-	D=
-	if need_explicit_dependencies ; then
-	    extract_dependency_libs "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la"
-	    [ -n "$dependency_libs" ] && D=" $dependency_libs"
-	fi
-	echo "$L-lxapian@LIBRARY_VERSION_SUFFIX@$D"
-	;;
+        ##UNINSTONLYBEGIN
+        if is_uninstalled ; then
+            if [ no = "$xo_lib_xapian" ]; then
+                echo "$0: Use libtool and '$PROG_NAME --ltlibs'" 1>&2
+            else
+                configure_ac='configure.in (or configure.ac)'
+                # If ac_top_srcdir isn't passed to us, we just end up looking
+                # in the current directory, which is a sensible fallback.
+                if [ -r "${ac_top_srcdir}configure.ac" ]; then
+                    configure_ac=configure.ac
+                elif [ -r "${ac_top_srcdir}configure.in" ]; then
+                    configure_ac=configure.in
+                fi
+                echo "$0: Add AC_PROG_LIBTOOL to your $configure_ac" 1>&2
+            fi
+            echo "to link with an uninstalled libxapian@LIBRARY_VERSION_SUFFIX@." 1>&2
+            exit 1
+        fi
+        ##UNINSTONLYEND
+        set_L_to_library_path
+        D=
+        if need_explicit_dependencies ; then
+            extract_dependency_libs "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la"
+            [ -n "$dependency_libs" ] && D=" $dependency_libs"
+        fi
+        echo "$L-lxapian@LIBRARY_VERSION_SUFFIX@$D"
+        ;;
 
     --ltlibs)
-	##UNINSTONLYBEGIN
-	if is_uninstalled ; then
-	    # Don't check if libxapian@LIBRARY_VERSION_SUFFIX@.la exists yet since we want to allow
-	    # configuring against a xapian-core tree which hasn't been built
-	    # yet (the top level bootstrap script relies on this).
-	    [ ./ != "$builddir" ] && F="$F$builddir"
-	    [ no = "$static" ] || F="-static-libtool-libs $F"
-	    echo "${F}libxapian@LIBRARY_VERSION_SUFFIX@.la"
-	    continue
-	fi
-	##UNINSTONLYEND
+        ##UNINSTONLYBEGIN
+        if is_uninstalled ; then
+            # Don't check if libxapian@LIBRARY_VERSION_SUFFIX@.la exists yet since we want to allow
+            # configuring against a xapian-core tree which hasn't been built
+            # yet (the top level bootstrap script relies on this).
+            [ ./ != "$builddir" ] && F="$F$builddir"
+            [ no = "$static" ] || F="-static-libtool-libs $F"
+            echo "${F}libxapian@LIBRARY_VERSION_SUFFIX@.la"
+            continue
+        fi
+        ##UNINSTONLYEND
 
-	# If we need to pull in dependency_libs, we need libxapian@LIBRARY_VERSION_SUFFIX@.la.
-	# Otherwise just use the appropriate -L and -l options.
-	# Upstream libtool currently never sets link_all_deplibs_CXX=no.
-	# Some Linux distros patch libtool to return no, and some have an
-	# unhelpful policy of not packaging .la files in an attempt to work
-	# around this.  So avoiding using libtool here gives more consistent
-	# behaviour.
-	if need_explicit_dependencies ; then
-	    if [ -f "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la" ]; then
-		echo "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la"
-		continue
-	    fi
+        # If we need to pull in dependency_libs, we need libxapian@LIBRARY_VERSION_SUFFIX@.la.
+        # Otherwise just use the appropriate -L and -l options.
+        # Upstream libtool currently never sets link_all_deplibs_CXX=no.
+        # Some Linux distros patch libtool to return no, and some have an
+        # unhelpful policy of not packaging .la files in an attempt to work
+        # around this.  So avoiding using libtool here gives more consistent
+        # behaviour.
+        if need_explicit_dependencies ; then
+            if [ -f "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la" ]; then
+                echo "@libdir@/libxapian@LIBRARY_VERSION_SUFFIX@.la"
+                continue
+            fi
 
-	    echo "$0: Can't find libxapian@LIBRARY_VERSION_SUFFIX@.la to link against." 1>&2
-	    exit 1
-	fi
+            echo "$0: Can't find libxapian@LIBRARY_VERSION_SUFFIX@.la to link against." 1>&2
+            exit 1
+        fi
 
-	set_L_to_library_path
-	echo "$L-lxapian@LIBRARY_VERSION_SUFFIX@"
-	;;
+        set_L_to_library_path
+        echo "$L-lxapian@LIBRARY_VERSION_SUFFIX@"
+        ;;
     esac
 done
 exit 0
