Use libtoolize path to determine aclocal dir
Previously we used the path to the libtool script, but in the
Debian packaging that's in libtool-bin which may not be installed
(and our build works without it).  We definitely require libtoolize
to be present, so use that instead.

We also now fail with a clear error if libtoolize isn't found on
PATH - previously we'd die with an obscure error due to "aclocal
-I -I /foo" being run, which results in the first -I taking the
second as its argument, and then "/foo" being interpreted as a
command line argument.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -612,7 +612,11 @@ if need_to_build $args libtool ; then
   export LIBTOOLIZE
   libtool_aclocal=$instdir/share/aclocal
 else
-  libtool_aclocal=`which libtool|sed 's!/bin/[^/]*$!/share/aclocal!'`
+  libtool_aclocal=`which libtoolize|sed 's!/bin/[^/]*$!/share/aclocal!'`
+  if [ -z "$libtool_aclocal" ] ; then
+    echo "libtoolize not found"
+    exit 1
+  fi
 fi
 # If the aclocal we're using is in a different prefix to the libtool we're
 # using, we probably need to tell aclocal where to look for our libtool's
