Merge useful changes from trunk, to allow bootstrapping from git.
git-svn-id: file:///home/xapian-svn/xapian/branches/1.2@17652 6b2f1b92-a4f3-0310-943f-de3cbe41748b

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -2,7 +2,7 @@
 # bootstrap a xapian source tree obtained from SVN to produce a tree like
 # you'd get from unpacking the results of "make dist"
 #
-# Copyright (C) 2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012 Olly Betts
+# Copyright (C) 2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013 Olly Betts
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License as
@@ -20,7 +20,7 @@
 # USA
 
 if [ "$1" = "--help" ] ; then
-  echo "$0 [--without-autotools|--clean]"
+  echo "$0 [--ftp] [--without-autotools|--clean]"
   exit 0
 fi
 
@@ -37,21 +37,34 @@ check_sha1sum() {
   checksum=$1
   tarball=$2
 
-  # BusyBox sha1sum doesn't know --version so just run to see it it works.
-  if echo "$checksum  $tarball"|${SHA1SUM-sha1sum} -c 2>/dev/null ; then
-    : # Checksum OK!
-  else
-    # Either sha1sum wasn't installed, or the checksum failed to match.
-    case `openssl sha1 "$tarball" 2>/dev/null` in
-      *$checksum) ;;
-      "") echo "Need sha1sum or openssl installed to check SHA1 checksums"
+  if [ -z "$SHA1SUM_TOOL" ] ; then
+    for SHA1SUM_TOOL in \
+	'${SHA1SUM-sha1sum} 2>/dev/null|cut -d\  -f1' \
+	'${SHASUM-shasum} 2>/dev/null|cut -d\  -f1' \
+	'$(OPENSSL-openssl} sha1 2>/dev/null|sed "s/.* //"' \
+	'' ; do
+      if [ -z "$SHA1SUM_TOOL" ] ; then
+	echo <<'END'
+Need sha1sum or shasum or openssl installed to check SHA1 checksums.
+Set environment variable SHA1SUM, SHASUM or OPENSSL if the tool isn't on
+your PATH.
+END
 	exit 1
-	;;
-      *)
-	echo "$tarball: computed SHA1 checksum did NOT match"
-	exit 1
-	;;
-    esac
+      fi
+      r=`:|eval "$SHA1SUM_TOOL"`
+      [ X"$r" != Xda39a3ee5e6b4b0d3255bfef95601890afd80709 ] || break
+    done
+  fi
+  r=`< $tarball eval "$SHA1SUM_TOOL"`
+  if [ X"$r" != X"$checksum" ] ; then
+    echo "$tarball: computed SHA1 checksum did NOT match"
+    echo "computed: $r with $SHA1SUM_TOOL"
+    echo "expected: $checksum"
+    ls -l $tarball
+    file $tarball || true
+    mv "$tarball" "$tarball.$r"
+    echo "Renamed $tarball to $tarball.$r"
+    exit 1
   fi
 }
 
@@ -60,6 +73,19 @@ lazy_build() {
   basename=$package-$2
   ext=$3
   checksum=$4
+  if [ "$ext" = "tar.xz" ] ; then
+    if [ -z "$xz_ok" ] ; then
+      if ${XZ-xz} --version > /dev/null 2>&1 ; then
+	xz_ok=1
+      else
+	xz_ok=0
+      fi
+    fi
+    if [ "$xz_ok" = 0 ] ; then
+      ext=$5
+      checksum=$6
+    fi
+  fi
   tarball=$basename.$ext
   case $basename in
     *[24680][a-z]) basename=`echo "$basename"|sed 's/[a-z]$//'` ;;
@@ -73,25 +99,55 @@ lazy_build() {
   if [ ! -f "$tarball" ] ; then
     if [ -z "$FETCH_URL_TOOL" ] ; then
       if ${WGET-wget} --version > /dev/null 2>&1 ; then
-	FETCH_URL_TOOL=${WGET-wget}
+	FETCH_URL_TOOL="${WGET-wget} -O-"
       elif ${CURL-curl} --version > /dev/null 2>&1 || [ "$?" = 2 ] ; then
-	# curl --version exists with code 2.
-	FETCH_URL_TOOL="${CURL-curl} -O"
+	# curl --version exits with code 2.
+	# -L is needed to follow HTTP redirects.
+	FETCH_URL_TOOL="${CURL-curl} -L"
+      elif ${LWP_REQUEST-lwp-request} -v > /dev/null 2>&1 || [ "$?" = 9 -o "$?" = 255 ] ; then
+	# lwp-request -v exits with code 9 (5.810) or 255 (6.03)
+	FETCH_URL_TOOL="${LWP_REQUEST-lwp-request} -mGET"
       else
-	echo "Neither wget nor curl found - set WGET or CURL to the full path," >&2
-	echo "or download $url to directory `pwd` by hand and rerun this script." >&2
+	cat <<END >&2
+Neither wget nor curl nor lwp-request found - install one of them or if already
+installed, set WGET, CURL or LWP_REQUEST to the full path.  Alternatively,
+download $url
+to directory `pwd`
+then rerun this script.
+END
 	exit 1
       fi
     fi
     case $basename in
     doxygen-*)
-      $FETCH_URL_TOOL "ftp://ftp.stack.nl/pub/users/dimitri/$tarball" ;;
+      if [ "$use_ftp" = yes ] ; then
+	url="ftp://ftp.stack.nl/pub/users/dimitri/$tarball"
+      else
+	url="http://ftp.stack.nl/pub/users/dimitri/$tarball"
+      fi ;;
+    file-*)
+      if [ "$use_ftp" = yes ] ; then
+	url="ftp://ftp.astron.com/pub/file/$tarball"
+      else
+	url="http://fossies.org/unix/misc/$tarball"
+      fi ;;
     *[13579][a-z])
       # GNU alpha release
-      $FETCH_URL_TOOL "ftp://alpha.gnu.org/gnu/$package/$tarball" ;;
+      if [ "$use_ftp" = yes ] ; then
+	url="ftp://alpha.gnu.org/gnu/$package/$tarball"
+      else
+	url="http://alpha.gnu.org/gnu/$package/$tarball"
+      fi ;;
     *)
-      $FETCH_URL_TOOL "ftp://ftp.gnu.org/gnu/$package/$tarball" ;;
+      if [ "$use_ftp" = yes ] ; then
+	url="ftp://ftp.gnu.org/gnu/$package/$tarball"
+      else
+	url="http://ftpmirror.gnu.org/$package/$tarball"
+      fi ;;
     esac
+    rm -f download.tmp
+    echo "Downloading <$url>"
+    $FETCH_URL_TOOL "$url" > download.tmp && mv download.tmp "$tarball"
   fi
 
   if [ -f "$stamp" ] ; then
@@ -104,11 +160,14 @@ lazy_build() {
     # Verify the tarball's checksum before building it.
     check_sha1sum "$checksum" "$tarball"
 
+    # Remove tarballs of other versions.
     for f in "$package"-* ; do
       [ "$f" = "$tarball" ] || rm -rf "$f"
     done
 
     case $ext in
+    tar.xz)
+      xz -dc "$tarball"| tar xf - ;;
     tar.bz2)
       bzip2 -dc "$tarball"| tar xf - ;;
     *)
@@ -137,6 +196,34 @@ lazy_build() {
   fi
 }
 
+handle_svn_external() {
+  path=$1
+  if [ ! -f "$path/.nobootstrap" ] ; then
+    revopt=$2
+    url=$3
+    if [ ! -d "$path" ] ; then
+      git svn init "$url" "$path"/
+    fi
+    (cd "$path" && git svn fetch "$revopt" && git reset --hard `git svn log "$revopt" --show-commit|perl -e '<>;<>=~/\| ([0-9a-f]+)/ ; print $1'`)
+  fi
+}
+
+handle_git_external() {
+  path=$1
+  if [ ! -f "$path/.nobootstrap" ] ; then
+    rev=$2
+    url=$3
+    if [ ! -d "$path" ] ; then
+      git clone --no-checkout -- "$url" "$path"
+    elif git reflog "$rev" -- 2>/dev/null ; then
+      : # Already have that revision locally
+    else
+      (cd "$path" && git fetch)
+    fi
+    (cd "$path" && git checkout "$rev")
+  fi
+}
+
 curdir=`pwd`
 
 # cd to srcdir if we aren't already there.
@@ -160,35 +247,78 @@ if [ -d ".git" ] ; then
     fi
   done
 
-  sed '/^\(swig\|xapian-applications\/omega\/common$\)/d' .git/info/exclude > .git/info/exclude~
+  if [ -f .git/info/exclude ] ; then
+    sed '/^\(swig\|xapian-applications\/omega\/common$\)/d' .git/info/exclude > .git/info/exclude~
+  else
+    [ -d .git/info ] || mkdir .git/info
+  fi
   cat <<END >> .git/info/exclude~
 swig
 xapian-applications/omega/common
 END
-  if cmp .git/info/exclude~ .git/info/exclude > /dev/null ; then
+  if [ -f .git/info/exclude ] && 
+     cmp .git/info/exclude~ .git/info/exclude > /dev/null ; then
     rm .git/info/exclude~
   else
     mv .git/info/exclude~ .git/info/exclude
   fi
 
-  # FIXME: Currently requires manual update...
-  #svn:externals revision for SWIG
-  rev=12767
-  if [ ! -d swig ] ; then
-    git svn init svn://svn.tartarus.org/swig/trunk/ swig/
-  fi
-  (cd swig && git svn fetch -r"$rev" && git svn rebase)
+  if git config --get svn-remote.svn.url >/dev/null ; then
+    # git repo checked out with git-svn from svn.xapian.org.
 
-  # FIXME: Currently requires manual update...
-  #svn:externals revision for xapian-applications/omega/common
-  # Note: this needs to be the exact revision of the previous change!
-  rev=16346
-  if [ ! -d xapian-applications/omega/common ] ; then
-    git svn init svn://svn.xapian.org/xapian/trunk/xapian-core/common xapian-applications/omega/common
+    # Pull in each svn:externals as a separate little git repo:
+    git svn show-externals | while read path revopt url ; do
+      # For example:
+      # /swig -r12724 svn://svn.tartarus.org/swig/trunk/
+      if [ -n "$url" ] ; then
+	case $path in
+	/swig)
+	  if [ -d swig/.git/svn ] ; then
+	    # Old git-svn checkout - move it aside rather than
+	    # deleting in case there are local changes.
+	    echo 'Moving old git-svn checkout of swig to swig.git-svn.old'
+	    echo 'If you have not modified it locally, you can safely delete'
+	    echo 'this now'
+	    mv swig swig.git-svn.old
+	  fi
+	  swig_origin_url=git://github.com/swig/swig.git
+	  handle_git_external swig 210266cd7004108b074fac9da4fc97d1df0adc53 "$swig_origin_url"
+	  ;;
+	/*)
+	  path=`echo "$path"|sed 's,^/,,'`
+	  handle_svn_external "$path" "$revopt" "$url"
+	  ;;
+	esac
+      fi
+    done
+  else
+    # git repo cloned from git.xapian.org or a mirror of it.
+
+    # If this tree is checked out from the github mirror, use the same access
+    # method for swig, so we avoid firewall issues.
+    origin_url=`git config remote.origin.url`
+    case $origin_url in
+      *[@/]github.com[:/]*)
+	swig_origin_url=`echo "X$origin_url"|sed 's/^X//;s!\([@/]github.com[:/]\).*!\1!'` ;;
+      *)
+	swig_origin_url=git://github.com/ ;;
+    esac
+    swig_origin_url=${swig_origin_url}swig/swig.git
+    handle_git_external swig 210266cd7004108b074fac9da4fc97d1df0adc53 "$swig_origin_url"
+
+    # Equivalent to r16346 in the Xapian SVN tree:
+    handle_git_external xapian-applications/omega/.common.git 5927a321a166c0870946bbc5d9f3de89db23e248 .
+    ln -sf .common.git/xapian-core/common xapian-applications/omega/common
   fi
-  (cd xapian-applications/omega/common && git svn fetch -r"$rev" && git svn rebase)
 fi
 
+# Prefer http downloads as they are more likely to work through firewalls.
+use_ftp=no
+if [ "$1" = "--ftp" ] ; then
+  shift
+  use_ftp=yes
+fi
+ 
 if [ "$1" = "--without-autotools" ] ; then
   shift
 else
@@ -209,6 +339,10 @@ else
   AUTOCONF=$instdir/bin/autoconf \
   lazy_build automake 1.11.6 tar.gz 29d7832b148e2157e03ad0d3620fbb7f5a13bc21
   lazy_build libtool 2.4 tar.gz 149e9d7a993b643d13149a94d07bbca1085e601c
+  if [ "$1" = "--deps=libmagic" ] ; then
+      shift
+      lazy_build file 5.10 tar.gz 72fd435e78955ee122b7b3d323ff2f92e6263e89
+  fi
 
   for v in $autotools ; do
      tool=`echo "$v"|tr A-Z a-z`
@@ -241,45 +375,55 @@ modules=
 for module in xapian-core xapian-applications/omega swig xapian-bindings ; do
   d=$module
   if [ -f "$d/configure.ac" -o -f "$d/configure.in" ] ; then
-    echo "Bootstrapping \`$module'"
-    [ -f "$d/preautoreconf" ] && "$d/preautoreconf"
-
-    # If we have a custom INSTALL file, preserve it since autoreconf insists on
-    # replacing INSTALL with "generic installation instructions" when --force
-    # is used.  Be careful to replace it if autoreconf fails.
-    if [ -f "$d/INSTALL" ] ; then
-      if grep 'generic installation instructions' "$d/INSTALL" >/dev/null 2>&1 ; then
-	:
-      else
-	mv -f "$d/INSTALL" "$d/INSTALL.preserved-by-bootstrap"
-      fi
-    fi
-
-    autoreconf_rc=
-    if [ swig = "$module" ] ; then
-      # SWIG provides its own bootstrapping script.
-      curdir=`pwd`
-      cd "$d"
-      ./autogen.sh || autoreconf_rc=$?
-      cd "$curdir"
-      # Use the uninstalled wrapper for the in-tree copy of SWIG.
-      intree_swig=yes
-    else
-      # Use --install as debian's autoconf wrapper uses 2.5X if it sees it
-      # (but it doesn't check for -i).
-      #
-      # Use --force so that we update files if autoconf, automake, or libtool
-      # has been upgraded.
-      ${AUTORECONF-autoreconf} --install --force "$d" || autoreconf_rc=$?
-    fi
-    if [ -f "$d/INSTALL.preserved-by-bootstrap" ] ; then
-      mv -f "$d/INSTALL.preserved-by-bootstrap" "$d/INSTALL"
-    fi
-    if [ -n "$autoreconf_rc" ] ; then
-      exit $autoreconf_rc
-    fi
-    modules="$modules $module"
+    :
+  else
+    # Skip any directories we can't bootstrap.
+    continue
   fi
+  if [ -f "$d/.nobootstrap" ] ; then
+    # Report why to save head scratching when someone forgets they created
+    # a .nobootstrap file.
+    echo "Skipping '$module' due to presence of '$d/.nobootstrap'."
+    continue
+  fi
+  echo "Bootstrapping \`$module'"
+  [ -f "$d/preautoreconf" ] && "$d/preautoreconf"
+
+  # If we have a custom INSTALL file, preserve it since autoreconf insists on
+  # replacing INSTALL with "generic installation instructions" when --force
+  # is used.  Be careful to replace it if autoreconf fails.
+  if [ -f "$d/INSTALL" ] ; then
+    if grep 'generic installation instructions' "$d/INSTALL" >/dev/null 2>&1 ; then
+      :
+    else
+      mv -f "$d/INSTALL" "$d/INSTALL.preserved-by-bootstrap"
+    fi
+  fi
+
+  autoreconf_rc=
+  if [ swig = "$module" ] ; then
+    # SWIG provides its own bootstrapping script.
+    curdir=`pwd`
+    cd "$d"
+    ./autogen.sh || autoreconf_rc=$?
+    cd "$curdir"
+    # Use the uninstalled wrapper for the in-tree copy of SWIG.
+    intree_swig=yes
+  else
+    # Use --install as debian's autoconf wrapper uses 2.5X if it sees it
+    # (but it doesn't check for -i).
+    #
+    # Use --force so that we update files if autoconf, automake, or libtool
+    # has been upgraded.
+    ${AUTORECONF-autoreconf} --install --force "$d" || autoreconf_rc=$?
+  fi
+  if [ -f "$d/INSTALL.preserved-by-bootstrap" ] ; then
+    mv -f "$d/INSTALL.preserved-by-bootstrap" "$d/INSTALL"
+  fi
+  if [ -n "$autoreconf_rc" ] ; then
+    exit $autoreconf_rc
+  fi
+  modules="$modules $module"
 done
 
 # Search::Xapian doesn't use autotools.
@@ -393,10 +537,13 @@ for d in $modules ; do
       cd "$d" && "$configure" ${1+"$@"}
       ;;
     xapian-core)
-      cd "$d" && "$configure" --enable-maintainer-mode --cache-file="$here/config.cache" ${1+"$@"}
+      cd "$d" && "$configure" --enable-maintainer-mode --disable-option-checking --cache-file="$here/config.cache" ${1+"$@"}
+      ;;
+    xapian-applications/omega)
+      cd "$d" && "$configure" --enable-maintainer-mode --disable-option-checking XAPIAN_CONFIG="$XAPIAN_CONFIG" CXXFLAGS="-I$srcdir/INST/include -L$srcdir/INST/lib" ${1+"$@"}
       ;;
     *)
-      cd "$d" && "$configure" --enable-maintainer-mode --cache-file="$here/config.cache" XAPIAN_CONFIG="$XAPIAN_CONFIG" ${1+"$@"}
+      cd "$d" && "$configure" --enable-maintainer-mode --disable-option-checking --cache-file="$here/config.cache" XAPIAN_CONFIG="$XAPIAN_CONFIG" ${1+"$@"}
       ;;
     esac
     cd "$here"
