bootstrap now generates configure to avoid users trying to run it too soon (it's stored inline as a here doc).  Remove configure on make distclean or maintainer-clean.
Only try to bootstrap xapian-applications that we know work (that's omega at
present).


git-svn-id: file:///home/xapian-svn/xapian/trunk@4796 6b2f1b92-a4f3-0310-943f-de3cbe41748b

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -38,7 +38,9 @@ case "$bison_version" in
 esac
 
 srcdir="`echo $0|sed 's![^/]*$!!'`"
-for module in xapian-core xapian-bindings xapian-examples xapian-applications/* ; do
+# don't try to build xapian-applications/dbtools or xapview - they need work.
+# ditto for cvssearch.
+for module in xapian-core xapian-bindings xapian-examples xapian-applications/omega ; do
   d="${srcdir}$module"
   if test -f "$d/configure.in" -o -f "$d/configure.ac" ; then
     echo "Bootstrapping \`$module'"
@@ -54,6 +56,74 @@ for module in xapian-core xapian-bindings xapian-examples xapian-applications/* 
     fi
   fi
 done
+
+# generate the top-level configure script
+rm -f configure.tmp
+cat <<'END_OF_CONFIGURE' > configure.tmp
+#!/bin/sh
+# configure each submodule in a xapian source tree
+# Generated by Xapian top-level bootstrap script.
+#
+# Copyright (C) 2003 Olly Betts
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License as
+# published by the Free Software Foundation; either version 2 of the
+# License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
+# USA
+
+trap 'echo "configure failed"' EXIT
+set -e
+srcdir_raw="`echo $0|sed 's![^/]*$!!'`"
+test -z "$srcdir_raw" && srcdir_raw=.
+srcdir="`cd \"$srcdir_raw\" && pwd`"
+dirs=
+here="`pwd`"
+XAPIAN_CONFIG="$here/xapian-core/xapian-config"
+export XAPIAN_CONFIG
+for d in xapian-core xapian-bindings xapian-examples xapian-applications/* ; do
+  if test -f "$srcdir/$d/configure" ; then
+    if test -d "$d" ; then : ; else
+      case "$d" in
+      xapian-applications/*) test -d xapian-applications || mkdir xapian-applications ;;
+      esac
+      mkdir "$d"
+    fi
+    echo "Configuring \`$d'"
+    cd "$d" && "$srcdir/$d/configure" ${1+"$@"}
+    cd "$here"
+    dirs="$dirs $d"
+  fi
+done
+
+rm -f Makefile.tmp
+echo "# Makefile generated by $0" > Makefile.tmp
+for target in all install uninstall install-strip clean distclean mostlyclean maintainer-clean dist check distcheck ; do
+  echo >> Makefile.tmp
+  echo "$target:" >> Makefile.tmp
+  for d in $dirs ; do
+    echo "	cd $d && \$(MAKE) $target" >> Makefile.tmp
+  done
+  case "$target" in
+    distclean|maintainer-clean) echo "	rm -f Makefile configure" >> Makefile.tmp ;;
+  esac
+done
+mv -f Makefile.tmp Makefile
+trap EXIT
+echo "Configured successfully - now run \"${MAKE-make}\""
+END_OF_CONFIGURE
+
+chmod +x configure.tmp
+mv -f configure.tmp configure
 
 trap EXIT
 echo "Bootstrapped successfully - now run \"${srcdir}configure\" and \"${MAKE-make}\""
