Merge bootstrap-with-autotools into bootstrap.  Add --without-autotools option to use what you have installed.  Reject libtool 1.5 as well as 1.4.  Only add -I to aclocal once, with the correct path.
git-svn-id: file:///home/xapian-svn/xapian/trunk@10861 6b2f1b92-a4f3-0310-943f-de3cbe41748b

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -19,18 +19,54 @@
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
 # USA
 
+if [ "$1" = "--help" ] ; then
+  echo "$0 [--without-autotools] [--clean]"
+  exit 0
+fi
+
 trap 'echo "Bootstrap failed"' EXIT
 set -e
 
-case `${LIBTOOLIZE-libtoolize} --version` in
-"")
-  echo "${LIBTOOLIZE-libtoolize} not found"
-  exit 1 ;;
-"libtoolize (GNU libtool) 1.4.*")
-  echo "${LIBTOOLIZE-libtoolize} is from libtool 1.4 which is too old - libtool 1.5 is required."
-  echo "If you have both installed, set LIBTOOLIZE to point to the correct version."
-  exit 1 ;;
-esac
+do_build_if_required() {
+  package=$1
+  basename=$package-$2
+  checksum=$3
+  tarball=$basename.tar.bz2
+  stamp=$package.stamp
+
+  # Download the tarball if required.
+  if [ ! -f "$tarball" ] ; then
+    wget "ftp://ftp.gnu.org/gnu/$package/$tarball"
+  fi
+
+  if [ -f "$stamp" ] ; then
+    find_stdout=`find "$stamp" -newer "$tarball" -print`
+  else
+    find_stdout=
+  fi
+
+  if [ -z "$find_stdout" ] ; then
+    # Verify tarball's checksum.
+    echo "$checksum  $tarball"|sha1sum -c
+
+    for f in "$package"-* ; do
+      [ "$f" = "$tarball" ] || rm -rf "$f"
+    done
+
+    bzip2 -dc "$tarball"| tar xf -
+
+    cd "$basename"
+    ./configure --prefix="$instdir"
+    make
+    make install
+    cd ..
+    rm -rf "$basename"
+
+    touch "$stamp"
+  fi
+}
+
+curdir=`pwd`
 
 # cd to srcdir if we aren't already there.
 srcdir=`echo "$0"|sed 's!/*[^/]*$!!'`
@@ -41,6 +77,86 @@ case $srcdir in
     cd "$srcdir" ;;
 esac
 
+if [ "$1" = "--without-autotools" ] ; then
+  shift
+else
+  if [ "$1" = "--clean" ] ; then
+    shift
+    rm -rf INST BUILD
+  fi
+
+  test -d INST || mkdir INST
+  instdir=`pwd`/INST
+
+  test -d BUILD || mkdir BUILD
+  cd BUILD
+
+  do_build_if_required() {
+    package=$1
+    basename=$package-$2
+    checksum=$3
+    tarball=$basename.tar.bz2
+    stamp=$package.stamp
+
+    # Download the tarball if required.
+    if [ ! -f "$tarball" ] ; then
+      wget "ftp://ftp.gnu.org/gnu/$package/$tarball"
+    fi
+
+    if [ -f "$stamp" ] ; then
+      find_stdout=`find "$stamp" -newer "$tarball" -print`
+    else
+      find_stdout=
+    fi
+
+    if [ -z "$find_stdout" ] ; then
+      # Verify tarball's checksum.
+      echo "$checksum  $tarball"|sha1sum -c
+
+      for f in "$package"-* ; do
+	[ "$f" = "$tarball" ] || rm -rf "$f"
+      done
+
+      bzip2 -dc "$tarball"| tar xf -
+
+      cd "$basename"
+      ./configure --prefix="$instdir"
+      make
+      make install
+      cd ..
+      rm -rf "$basename"
+
+      touch "$stamp"
+    fi
+  }
+
+  do_build_if_required autoconf 2.62 de2b6f57da07427794c56e25844e31f35fc46755
+  do_build_if_required automake 1.10.1 cd2e0f7054d4edc75cbf87cd8a92962b3b417b74
+  do_build_if_required libtool 2.2.4 bc485fd07c8b12820234240e9ef41dba693af2b7
+
+  for t in autoreconf autoconf autoheader autom4te automake aclocal libtoolize
+  do
+     var=`echo "$t"|tr a-z A-Z`
+     eval "$var=\"\$instdir\"/bin/$t;export $var"
+  done
+
+  cd ..
+fi
+
+case `${LIBTOOLIZE-libtoolize} --version` in
+"")
+  echo "${LIBTOOLIZE-libtoolize} not found"
+  exit 1 ;;
+"libtoolize (GNU libtool) 1.4.*")
+  echo "${LIBTOOLIZE-libtoolize} is from libtool 1.4 which is too old - libtool 2.2 is required."
+  echo "If you have both installed, set LIBTOOLIZE to point to the correct version."
+  exit 1 ;;
+"libtoolize (GNU libtool) 1.5.*")
+  echo "${LIBTOOLIZE-libtoolize} is from libtool 1.5 which is too old - libtool 2.2 is required."
+  echo "If you have both installed, set LIBTOOLIZE to point to the correct version."
+  exit 1 ;;
+esac
+
 SWIG=""
 # Don't try to build xapian-applications/dbtools or xapview - they need work.
 # As does cvssearch.
@@ -49,7 +165,7 @@ SWIG=""
 modules=
 for module in xapian-core xapian-applications/omega swig xapian-bindings ; do
   d=$module
-  if test -f "$d/configure.in" -o -f "$d/configure.ac" ; then
+  if test -f "$d/configure.ac" -o -f "$d/configure.in" ; then
     echo "Bootstrapping \`$module'"
     test -f "$d/preautoreconf" && "$d/preautoreconf"
     # Use --install as debian's autoconf wrapper uses 2.5X if it sees it
@@ -87,16 +203,6 @@ for module in xapian-core xapian-applications/omega swig xapian-bindings ; do
       exit $autoreconf_rc
     fi
     modules="$modules $module"
-
-    if test xapian-core = "$module" ; then
-      if test -d "$d/m4-macros" ; then
-	# Pass extra option to ACLOCAL so xapian.m4 can be found by other
-	# modules.
-	aclocal_dir=`cd "$d/m4-macros" && pwd`
-	ACLOCAL="${ACLOCAL-aclocal} -I $aclocal_dir"
-	export ACLOCAL
-      fi
-    fi
   fi
 done
 
@@ -107,7 +213,7 @@ cat <<'TOP_OF_CONFIGURE' > configure.tmp
 # configure each submodule in a xapian source tree
 # Generated by Xapian top-level bootstrap script.
 #
-# Copyright (C) 2003,2004,2007 Olly Betts
+# Copyright (C) 2003,2004,2007,2008 Olly Betts
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License as
@@ -161,7 +267,7 @@ done
 cat <<'END_OF_CONFIGURE' >> configure.tmp
 dirs=
 XAPIAN_CONFIG=$here/xapian-core/xapian-config
-ACLOCAL="${ACLOCAL-aclocal} -I $srcdir/xapian-core/m4"
+ACLOCAL="${ACLOCAL-aclocal} -I $srcdir/xapian-core/m4-macros"
 for d in $modules ; do
   if test "$here" = "$srcdir" ; then
     configure=./configure
