Check that libtoolize is found and isn't from libtool 1.4.
git-svn-id: file:///home/xapian-svn/xapian/trunk@6933 6b2f1b92-a4f3-0310-943f-de3cbe41748b

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -22,6 +22,16 @@
 trap 'echo "Bootstrap failed"' EXIT
 set -e
 
+case `${LIBTOOLIZE-libtoolize} --version` in
+"")
+  echo "${LIBTOOLIZE-libtoolize} not found"
+  exit 1 ;;
+"libtoolize (GNU libtool) 1.4.*")
+  echo "${LIBTOOLIZE-libtoolize} is from libtool 1.4 which is too old - libtool 1.5 is required."
+  echo "If you have both installed, set LIBTOOLIZE to point to the correct version."
+  exit 1 ;;
+esac
+
 srcdir="`echo $0|sed 's![^/]*$!!'`"
 # Don't try to build xapian-applications/dbtools or xapview - they need work.
 # As does cvssearch.
