bootstrap: Show config.log if configure fails
Motivated by wanting to see it in CI, but it seems useful in general.
If it proves more annoying than useful then we can make it conditional
on an environment variable or something.

(cherry picked from commit 4e83ddfc96679f66029c26e4b84c22839302cd5f)

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -831,6 +831,8 @@ for d in $modules ; do
       mkdir "$d"
     fi
     echo "Configuring \`$d'"
+    # Replace EXIT trap with one which shows `config.log`.
+    trap 'if [ -f config.log ]; then echo "configure failed, config.log was:"; sed "s/^/| /" config.log else echo "configure failed"; fi' EXIT
     # Use a shared config.cache for speed and to save a bit of diskspace, but
     # don't share it with SWIG just in case it manages to probe and cache
     # different answers (e.g. because it uses a C compiler).
@@ -887,6 +889,8 @@ for d in $modules ; do
       cd "$d" && "$configure" --enable-maintainer-mode --disable-option-checking --cache-file="$here/config.cache" XAPIAN_CONFIG="$XAPIAN_CONFIG" ${1+"$@"}
       ;;
     esac
+    # Restore EXIT trap.
+    trap 'echo "configure failed"' EXIT
     cd "$here"
     dirs="$dirs $d"
     revdirs="$d $revdirs"
