Update with changes from trunk to revision 11599.
git-svn-id: file:///home/xapian-svn/xapian/branches/geospatial@11616 6b2f1b92-a4f3-0310-943f-de3cbe41748b

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -19,78 +19,197 @@
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
 # USA
 
+if [ "$1" = "--help" ] ; then
+  echo "$0 [--without-autotools|--clean]"
+  exit 0
+fi
+
 trap 'echo "Bootstrap failed"' EXIT
 set -e
+
+# The variables which specify the autotools to use.
+autotools="AUTORECONF AUTOCONF AUTOHEADER AUTOM4TE AUTOMAKE ACLOCAL LIBTOOLIZE"
+
+# Tool for downloading a file from a URL (currently wget or curl).
+FETCH_URL_TOOL=
+
+lazy_build() {
+  package=$1
+  basename=$package-$2
+  ext=$3
+  checksum=$4
+  tarball=$basename.$ext
+  case $basename in
+    *[a-z]) basename=`echo "$basename"|sed 's/[a-z]$//'` ;;
+  esac
+
+  # Create the stamp file in INST so that rerunning bootstrap after
+  # "rm -rf INST" recovers nicely.
+  stamp=../INST/$package.stamp
+
+  # Temporary measure to "upgrade" from having the stamp file in BUILD.  Doing
+  # this isn't vital but saves having to rebuild needlessly and cleans up the
+  # old stamp file too.
+  # FIXME: remove once everyone has had a chance to re-bootstrap.
+  test ! -f "$package.stamp" || mv "$package.stamp" "$stamp"
+
+  # Download the tarball if required.
+  if [ ! -f "$tarball" ] ; then
+    if [ -z "$FETCH_URL_TOOL" ] ; then
+      if ${WGET-wget} --version > /dev/null 2>&1 ; then
+	FETCH_URL_TOOL=${WGET-wget}
+      elif ${CURL-curl} --version > /dev/null 2>&1 || [ "$?" = 2 ] ; then
+	# curl --version exists with code 2.
+	FETCH_URL_TOOL=${CURL-curl}
+      else
+	echo "Neither wget nor curl found - set WGET or CURL to the full path," >&2
+	echo "or download $url to directory `pwd` by hand and rerun this script." >&2
+	exit 1
+      fi
+    fi
+    $FETCH_URL_TOOL "ftp://ftp.gnu.org/gnu/$package/$tarball"
+  fi
+
+  if [ -f "$stamp" ] ; then
+    find_stdout=`find "$stamp" -newer "$tarball" -print`
+  else
+    find_stdout=
+  fi
+
+  if [ -z "$find_stdout" ] ; then
+    # Verify the tarball's checksum before building it.
+    echo "$checksum  $tarball"|sha1sum -c
+
+    for f in "$package"-* ; do
+      [ "$f" = "$tarball" ] || rm -rf "$f"
+    done
+
+    case $ext in
+    tar.bz2)
+      bzip2 -dc "$tarball"| tar xf - ;;
+    *)
+      gzip -dc "$tarball"| tar xf - ;;
+    esac
+
+    cd "$basename"
+    ./configure --prefix="$instdir"
+    make
+    make install
+    cd ..
+    rm -rf "$basename"
+
+    touch "$stamp"
+  fi
+}
+
+curdir=`pwd`
+
+# cd to srcdir if we aren't already there.
+srcdir=`echo "$0"|sed 's!/*[^/]*$!!'`
+case $srcdir in
+  ""|.)
+    srcdir=. ;;
+  *)
+    cd "$srcdir" ;;
+esac
+
+if [ "$1" = "--without-autotools" ] ; then
+  shift
+else
+  if [ "$1" = "--clean" ] ; then
+    shift
+    rm -rf INST
+    # FIXME: remove once everyone has had a chance to re-bootstrap.
+    rm -f INST BUILD/*.stamp
+  fi
+
+  [ -d INST ] || mkdir INST
+  instdir=`pwd`/INST
+
+  [ -d BUILD ] || mkdir BUILD
+  cd BUILD
+
+  # The last field is the SHA1 checksum of the tarball.
+  lazy_build autoconf 2.63 tar.bz2 f15e14aa34acf871b47f659ef99a2e6707db4a18
+  lazy_build automake 1.10.1 tar.bz2 cd2e0f7054d4edc75cbf87cd8a92962b3b417b74
+  lazy_build libtool 2.2.6a tar.gz 7b547877b1b78b547343e4678a531aece8949904
+
+  for v in $autotools ; do
+     tool=`echo "$v"|tr A-Z a-z`
+     eval "$v=\"\$instdir\"/bin/$tool;export $v"
+  done
+
+  cd ..
+fi
 
 case `${LIBTOOLIZE-libtoolize} --version` in
 "")
   echo "${LIBTOOLIZE-libtoolize} not found"
   exit 1 ;;
 "libtoolize (GNU libtool) 1.4.*")
-  echo "${LIBTOOLIZE-libtoolize} is from libtool 1.4 which is too old - libtool 1.5 is required."
+  echo "${LIBTOOLIZE-libtoolize} is from libtool 1.4 which is too old - libtool 2.2 is required."
+  echo "If you have both installed, set LIBTOOLIZE to point to the correct version."
+  exit 1 ;;
+"libtoolize (GNU libtool) 1.5.*")
+  echo "${LIBTOOLIZE-libtoolize} is from libtool 1.5 which is too old - libtool 2.2 is required."
   echo "If you have both installed, set LIBTOOLIZE to point to the correct version."
   exit 1 ;;
 esac
 
-srcdir=`echo "$0"|sed 's![^/]*$!!'`
-SWIG=""
-# Don't try to build xapian-applications/dbtools or xapview - they need work.
-# As does cvssearch.
+ACLOCAL="${ACLOCAL-aclocal} -I `pwd`/xapian-core/m4-macros"
+
+intree_swig=no
 # We no longer snapshot xapian-applications/queryserver since it hasn't seen a
 # check-in for ages.
 modules=
 for module in xapian-core xapian-applications/omega swig xapian-bindings ; do
-  d=${srcdir}$module
-  if test -f "$d/configure.in" -o -f "$d/configure.ac" ; then
+  d=$module
+  if [ -f "$d/configure.ac" -o -f "$d/configure.in" ] ; then
     echo "Bootstrapping \`$module'"
-    test -f "$d/preautoreconf" && "$d/preautoreconf"
-    # Use --install as debian's autoconf wrapper uses 2.5X if it sees it
-    # (but it doesn't check for -i).
-    #
-    # Use --force so that we update files if autoconf, automake, or libtool
-    # has been upgraded.
-    #
+    [ -f "$d/preautoreconf" ] && "$d/preautoreconf"
+
     # If we have a custom INSTALL file, preserve it since autoreconf insists on
     # replacing INSTALL with "generic installation instructions" when --force
     # is used.  Be careful to replace it if autoreconf fails.
-    if test -f "$d/INSTALL" ; then
+    if [ -f "$d/INSTALL" ] ; then
       if grep 'generic installation instructions' "$d/INSTALL" >/dev/null 2>&1 ; then
 	:
       else
 	mv -f "$d/INSTALL" "$d/INSTALL.preserved-by-bootstrap"
       fi
     fi
+
     autoreconf_rc=
-    if test swig = "$module" ; then
+    if [ swig = "$module" ] ; then
       # SWIG provides its own bootstrapping script.
       curdir=`pwd`
       cd "$d"
       ./autogen.sh || autoreconf_rc=$?
       cd "$curdir"
       # Use the uninstalled wrapper for the in-tree copy of SWIG.
-      SWIG="\$here/swig/preinst-swig"
+      intree_swig=yes
     else
+      # Use --install as debian's autoconf wrapper uses 2.5X if it sees it
+      # (but it doesn't check for -i).
+      #
+      # Use --force so that we update files if autoconf, automake, or libtool
+      # has been upgraded.
       ${AUTORECONF-autoreconf} --install --force "$d" || autoreconf_rc=$?
     fi
-    if test -f "$d/INSTALL.preserved-by-bootstrap" ; then
+    if [ -f "$d/INSTALL.preserved-by-bootstrap" ] ; then
       mv -f "$d/INSTALL.preserved-by-bootstrap" "$d/INSTALL"
     fi
-    if test -n "$autoreconf_rc" ; then
+    if [ -n "$autoreconf_rc" ] ; then
       exit $autoreconf_rc
     fi
     modules="$modules $module"
-
-    if test xapian-core = "$module" ; then
-      if test -d "$d/m4" ; then
-	# Pass extra option to ACLOCAL so xapian.m4 can be found by other
-	# modules.
-	aclocal_dir=`cd "$d/m4" && pwd`
-	ACLOCAL="${ACLOCAL-aclocal} -I $aclocal_dir"
-	export ACLOCAL
-      fi
-    fi
   fi
 done
+
+# Search::Xapian doesn't use autotools.
+if [ -f "search-xapian/Makefile.PL" ] ; then
+  modules="$modules search-xapian"
+fi
 
 # Generate the top-level configure script.
 rm -f configure.tmp
@@ -99,7 +218,7 @@ cat <<'TOP_OF_CONFIGURE' > configure.tmp
 # configure each submodule in a xapian source tree
 # Generated by Xapian top-level bootstrap script.
 #
-# Copyright (C) 2003,2004,2007 Olly Betts
+# Copyright (C) 2003,2004,2007,2008 Olly Betts
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License as
@@ -134,30 +253,53 @@ done
 here=`pwd`
 TOP_OF_CONFIGURE
 
-# Produce an absolute version of srcdir.
-srcdir_abs=`cd "${srcdir-.}"&&pwd`
+# Produce an absolute path to srcdir.
+srcdir_abs=`pwd`
 # This section is unquoted so we can substitute variables.
 cat <<MIDDLE_OF_CONFIGURE >> configure.tmp
 srcdir="$srcdir_abs"
 modules="$modules"
-test -z "$SWIG" || : \${SWIG="$SWIG"}
-export SWIG
 MIDDLE_OF_CONFIGURE
+
+vars=
+if [ yes = "$intree_swig" ] ; then
+  # We want the path to SWIG to point into srcdir, which isn't known until
+  # configure-time, so we need to expand $here in configure.  We can't just set
+  # SWIG here and let the case below handle it as that would escape the value
+  # such that $here didn't get expanded at all.
+  echo ': ${SWIG="$here/swig/preinst-swig"}' >> configure.tmp
+  echo "export SWIG" >> configure.tmp
+  vars=' SWIG=$here/swig/preinst-swig'
+  # Kill any existing setting of SWIG so that we don't try to handle it again
+  # below.
+  SWIG=
+fi
+for tool in SWIG $autotools ; do
+  eval "val=\$$tool"
+  if [ -n "$val" ] ; then
+    echo ': ${'"$tool=\"$val\""'}' >> configure.tmp
+    echo "export $tool" >> configure.tmp
+    vars="$vars $tool='"`echo "$val"|sed 's/\(['"\\'"']\)/\\\1/g'`"'"
+  fi
+done
+if [ -n "$vars" ] ; then
+  # $vars will always have a leading space.
+  echo "set$vars "'"$@"' >> configure.tmp
+fi
 
 cat <<'END_OF_CONFIGURE' >> configure.tmp
 dirs=
 XAPIAN_CONFIG=$here/xapian-core/xapian-config
-ACLOCAL="${ACLOCAL-aclocal} -I $srcdir/xapian-core/m4"
 for d in $modules ; do
-  if test "$here" = "$srcdir" ; then
+  if [ "$here" = "$srcdir" ] ; then
     configure=./configure
   else
     configure=$srcdir/$d/configure
   fi
-  if test -f "$configure" ; then
-    if test -d "$d" ; then : ; else
+  if [ -f "$configure" ] ; then
+    if [ -d "$d" ] ; then : ; else
       case $d in
-      xapian-applications/*) test -d xapian-applications || mkdir xapian-applications ;;
+      xapian-applications/*) [ -d xapian-applications ] || mkdir xapian-applications ;;
       esac
       mkdir "$d"
     fi
@@ -172,8 +314,19 @@ for d in $modules ; do
     xapian-core)
       cd "$d" && "$configure" --enable-maintainer-mode --cache-file="$here/config.cache" ${1+"$@"}
       ;;
+    search-xapian)
+      # Extract any CXX=... argument from those passed to us.
+      unset cxxarg
+      for arg
+      do
+      	case $arg in
+	  CXX=*) cxxarg=$arg ;;
+	esac
+      done
+      cd "$d" && perl Makefile.PL XAPIAN_CONFIG="$XAPIAN_CONFIG" ${cxxarg+"$cxxarg"}
+      ;;
     *)
-      cd "$d" && "$configure" --enable-maintainer-mode --cache-file="$here/config.cache" XAPIAN_CONFIG="$XAPIAN_CONFIG" ACLOCAL="$ACLOCAL" ${1+"$@"}
+      cd "$d" && "$configure" --enable-maintainer-mode --cache-file="$here/config.cache" XAPIAN_CONFIG="$XAPIAN_CONFIG" ${1+"$@"}
       ;;
     esac
     cd "$here"
@@ -188,23 +341,29 @@ for target in all install uninstall install-strip clean distclean mostlyclean ma
   echo >> Makefile.tmp
   echo "$target:" >> Makefile.tmp
   for d in $dirs ; do
-    if test swig = "$d" ; then
-      case $target in
-	install*|uninstall|dist|check|distcheck)
-	  ;;
-	all)
-	  echo "	cd $d && \$(MAKE)" >> Makefile.tmp ;;
-	mostlyclean)
-	  echo "	cd $d && \$(MAKE) clean" >> Makefile.tmp ;;
-	*)
-	  echo "	cd $d && \$(MAKE) $target" >> Makefile.tmp ;;
-      esac
-    else
-      echo "	cd $d && \$(MAKE) $target" >> Makefile.tmp
-    fi
+    case $d,$target in
+    swig,install*|swig,uninstall|swig,dist|swig,check|swig,distcheck|swig,all)
+      # Need to ensure swig is built before "make dist", "make check", etc.
+      echo "	cd $d && \$(MAKE)" >> Makefile.tmp ;;
+    swig,mostlyclean|search-xapian,mostlyclean)
+      echo "	cd $d && \$(MAKE) clean" >> Makefile.tmp ;;
+    search-xapian,install-strip)
+      echo "	cd $d && \$(MAKE) install" >> Makefile.tmp ;;
+    search-xapian,maintainer-clean)
+      echo "	cd $d && \$(MAKE) realclean" >> Makefile.tmp ;;
+    search-xapian,distcheck)
+      echo "	cd $d && \$(MAKE) disttest" >> Makefile.tmp ;;
+    xapian-bindings,distcheck)
+      # FIXME: distcheck doesn't currently work for xapian-bindings because
+      # xapian-core isn't installed.
+      echo "	cd $d && \$(MAKE) check dist" >> Makefile.tmp ;;
+    *)
+      echo "	cd $d && \$(MAKE) $target" >> Makefile.tmp ;;
+    esac
   done
   case $target in
-    distclean|maintainer-clean) echo "	rm -f Makefile configure config.cache" >> Makefile.tmp ;;
+    distclean) echo "	rm -f Makefile config.cache" >> Makefile.tmp ;;
+    maintainer-clean) echo "	rm -f Makefile configure config.cache" >> Makefile.tmp ;;
   esac
 done
 mv -f Makefile.tmp Makefile
@@ -216,4 +375,4 @@ chmod +x configure.tmp
 mv -f configure.tmp configure
 
 trap - EXIT
-echo "Bootstrapped successfully - now run \"./configure\" and \"${MAKE-make}\""
+echo "Bootstrapped successfully - now run \"$srcdir/configure\" and \"${MAKE-make}\""
