omegatest: Factor out functions for error/warning tests

diff --git a/xapian-applications/omega/omegatest b/xapian-applications/omega/omegatest
--- a/xapian-applications/omega/omegatest
+++ b/xapian-applications/omega/omegatest
@@ -1,7 +1,7 @@
 #!/bin/sh
 # omegatest: Test omega CGI
 #
-# Copyright (C) 2015,2016,2017,2018,2019,2020,2021 Olly Betts
+# Copyright (C) 2015-2022 Olly Betts
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License as
@@ -86,6 +86,97 @@ qtestcase() {
     expected="Query($1)"
     shift
     testcase "$expected" "$@"
+}
+
+# Test scriptindex gives expected error.
+#
+# Parameters:
+# * what: text to report to describe situation
+# * expect: expected glob pattern stdout+stderr should match
+# * (optional) input: input to feed scriptindex; can contain \n, etc escapes
+#   (default: /dev/null)
+#
+# Uses database $TEST_DB and index script $TEST_INDEXSCRIPT.
+test_scriptindex_error() {
+  what=$1
+  expect=$2
+  input=$3
+  rm -rf "$TEST_DB"
+  rc=0
+  case $input in
+  "")
+    out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
+    ;;
+  *%*)
+    # Escape any % by doubling.
+    input=`printf '%s' "$input"|sed 's/%/%%/g'`
+    out=`printf "$input"|$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" 2>&1` || rc=$?
+    ;;
+  *)
+    out=`printf "$input"|$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" 2>&1` || rc=$?
+    ;;
+  esac
+  if [ $rc -eq 0 ] ; then
+    printf "scriptindex didn't exit with non-zero return code for %s"'\n' "$what"
+    printf 'Output: %s\n' "$out"
+    failed=`expr $failed + 1`
+  else
+    case $out in
+      $expect) ;; # OK
+      *)
+	printf "scriptindex didn't give expected error for %s"'\n' "$what"
+	printf 'Expect: %s\n' "$expect"
+	printf 'Output: %s\n' "$out"
+	failed=`expr $failed + 1`
+	;;
+    esac
+  fi
+}
+
+# Test scriptindex gives expected warning.
+#
+# Parameters:
+# * what: text to report to describe situation
+# * expect: expected glob pattern stdout+stderr should match
+# * (optional) input: input to feed scriptindex; can contain \n, etc escapes
+#   (default: /dev/null)
+#
+# Uses database $TEST_DB and index script $TEST_INDEXSCRIPT.
+test_scriptindex_warning() {
+  what=$1
+  expect="$2
+records (added, replaced, deleted) = (*, *, *)"
+  input=$3
+  rm -rf "$TEST_DB"
+  rc=0
+  case $input in
+  "")
+    out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
+    ;;
+  *%*)
+    # Escape any % by doubling.
+    input=`printf '%s' "$input"|sed 's/%/%%/g'`
+    out=`printf "$input"|$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" 2>&1` || rc=$?
+    ;;
+  *)
+    out=`printf "$input"|$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" 2>&1` || rc=$?
+    ;;
+  esac
+  if [ $rc -ne 0 ] ; then
+    printf "scriptindex gave an error rather than the expected warning for %s"'\n' "$what"
+    printf 'Output: %s\n' "$out"
+    failed=`expr $failed + 1`
+  else
+    case $out in
+      $expect) ;; # OK
+      *)
+	printf "scriptindex didn't give expected warning for %s"'\n' "$what"
+	printf 'Expect: %s\n' "$expect"
+	printf 'Output: %s\n' "$out"
+	failed=`expr $failed + 1`
+	;;
+    esac
+  fi
 }
 
 unset FAKE_NOW
@@ -1101,94 +1192,35 @@ testcase '|3|2|1|' P=test
 
 # Test useless action warnings.
 printf 'foo : index weight=2' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-if $SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1 \
-    | grep -q ":1:13: warning: Index action 'weight' has no effect" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected warning for useless 'weight' action"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_warning "useless 'weight' action" \
+  "$TEST_INDEXSCRIPT:1:13: warning: Index action 'weight' has no effect*"
+
 printf 'foo : weight=2 weight=3 index' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-if $SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1 \
-    | grep -q ":1:7: warning: Index action 'weight' has no effect" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected warning for useless 'weight' action"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_warning "useless 'weight' action" \
+  "$TEST_INDEXSCRIPT:1:7: warning: Index action 'weight' has no effect*"
+
 printf 'foo : index lower' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-if $SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1 \
-    | grep -q ":1:13: warning: Index action 'lower' has no effect" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected warning for useless 'lower' action"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_warning "useless 'lower' action" \
+  "$TEST_INDEXSCRIPT:1:13: warning: Index action 'lower' has no effect*"
 
 # Test bad fieldname errors.
 printf 'foo *bar : index' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-rc=0
-out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
-if [ $rc -eq 0 ] ; then
-    echo "scriptindex didn't exit with non-zero return code on bad fieldname"
-    failed=`expr $failed + 1`
-elif printf '%s' "$out" \
-    | grep -q ":1:5: error: field name must start with alphanumeric" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected error for a bad fieldname"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_error 'bad fieldname' \
+  "$TEST_INDEXSCRIPT:1:5: error: field name must start with alphanumeric"
+
 printf 'foo b!ar : index' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-rc=0
-out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
-if [ $rc -eq 0 ] ; then
-    echo "scriptindex didn't exit with non-zero return code on bad fieldname"
-    failed=`expr $failed + 1`
-elif printf '%s' "$out" \
-    | grep -q ":1:6: error: bad character '!' in fieldname" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected error for a bad fieldname"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_error 'bad fieldname' \
+  "$TEST_INDEXSCRIPT:1:6: error: bad character '!' in fieldname"
 
 # Test unwanted action argument.
 printf 'foo : spell=test index' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-rc=0
-out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
-if [ $rc -eq 0 ] ; then
-    echo "scriptindex didn't exit with non-zero return code on unwanted action argument"
-    failed=`expr $failed + 1`
-elif printf '%s' "$out" \
-    | grep -q ":1:12: error: Index action 'spell' doesn't take an argument" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected error for unwanted action argument"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_error 'unwanted action argument' \
+  "$TEST_INDEXSCRIPT:1:12: error: Index action 'spell' doesn't take an argument"
 
 # Test missing closing quote.
 printf 'foo : index="XFOO' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-rc=0
-out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
-if [ $rc -eq 0 ] ; then
-    echo "scriptindex didn't exit with non-zero return code for missing closing quote"
-    failed=`expr $failed + 1`
-elif printf '%s' "$out" \
-    | grep -q ":1:18: error: No closing quote" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected error for missing closing quote"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_error 'missing closing quote' \
+  "$TEST_INDEXSCRIPT:1:18: error: No closing quote"
 
 # Feature tests for scriptindex `termprefix` and `unprefix` actions.
 printf '$termprefix{$cgi{B}}|$unprefix{$cgi{B}}' > "$TEST_TEMPLATE"
@@ -1330,14 +1362,8 @@ fi
 
 # Test we check for hash's argument being an integer (new in 1.4.6).
 printf 'url : hash=37.3 boolean=Q unique=Q' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-if $SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1 \
-    | grep -q ":1:14: warning: Index action 'hash' takes an integer argument" ; then
-    : # OK
-else
-    echo "scriptindex didn't reject 'hash' with a non-integer argument"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_warning "'hash' with a non-integer argument" \
+  "$TEST_INDEXSCRIPT:1:14: warning: Index action 'hash' takes an integer argument"
 
 # Test we give a helpful error for an action with a digit in (regression
 # test for fix in 1.4.6).
@@ -1345,19 +1371,8 @@ fi
 # This used to give the confusing:
 # Unknown index action ''
 printf 'url : index4' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-rc=0
-out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
-if [ $rc -eq 0 ] ; then
-    echo "scriptindex didn't exit with non-zero return code for bad index action with a digit"
-    failed=`expr $failed + 1`
-elif printf '%s' "$out" \
-    | grep -q ":1:7: error: Unknown index action 'index4'" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected error for bad index action with a digit"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_error 'bad index action with a digit' \
+  "$TEST_INDEXSCRIPT:1:7: error: Unknown index action 'index4'"
 
 # Test we give a helpful error if an = sign is missed out before an optional
 # numeric argument (regression test for fix in 1.4.6).
@@ -1365,19 +1380,8 @@ fi
 # This used to give the confusing:
 # Unknown index action ''
 printf 'url : hash 42' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-rc=0
-out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
-if [ $rc -eq 0 ] ; then
-    echo "scriptindex didn't exit with non-zero return code for a missing equals sign"
-    failed=`expr $failed + 1`
-elif printf '%s' "$out" \
-    | grep -q ":1:12: error: Unknown index action '42'" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected error for a missing equals sign"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_error 'missing equals sign' \
+  "$TEST_INDEXSCRIPT:1:12: error: Unknown index action '42'"
 
 # Test we warn about spaces before and after '='.
 #
@@ -1387,23 +1391,12 @@ fi
 #
 # url : field= hash boolean=Q unique=Q
 printf 'url : field= hash boolean=Q unique=Q' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-if $SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1 \
-    | grep -q ":1:13: warning: putting spaces between '=' and the argument is deprecated" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected warning for space after '='"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_warning 'space after "="' \
+  "$TEST_INDEXSCRIPT:1:13: warning: putting spaces between '=' and the argument is deprecated"
+
 printf 'url : field =link' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-if $SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1 \
-    | grep -q ":1:12: warning: putting spaces between the action and '=' is deprecated" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected warning for space before '='"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_warning 'space before "="' \
+  "$TEST_INDEXSCRIPT:1:12: warning: putting spaces between the action and '=' is deprecated"
 
 # Feature tests for scriptindex `date` action.
 printf '%s\n' 'd : date=unix' 'g : date=unixutc' > "$TEST_INDEXSCRIPT"
@@ -1489,23 +1482,9 @@ testcase '%80:%A3:%1F%A4FS%60'
 
 # Feature tests for scriptindex `load` action.
 printf '%s\n' 'file : load field' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-rc=0
-out=`echo 'file='|$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" 2>&1 > /dev/null || rc=$?`
-if [ $rc -ne 0 ] ; then
-  echo "scriptindex gave error for empty filename in load action"
-  printf '%s\n' "$out"
-  failed=`expr $failed + 1`
-else
-  case $out in
-    *':1: warning: Empty filename in LOAD action') ;;
-    *)
-      echo "scriptindex didn't give expected warning for empty filename in load action"
-      printf '%s\n' "$out"
-      failed=`expr $failed + 1`
-      ;;
-  esac
-fi
+test_scriptindex_warning 'empty filename in load action' \
+  "<stdin>:1: warning: Empty filename in LOAD action" \
+  'file='
 
 # Feature tests for quoted arguments.
 printf 'DATE : field="  spaces  " date="yyyymmdd"\nTEXT: index="S"\n' > "$TEST_INDEXSCRIPT"
@@ -1541,20 +1520,8 @@ for badesc in \
     '"\x1g"' \
     ; do
     printf '%s' "x: split=$badesc" > "$TEST_INDEXSCRIPT"
-    rm -rf "$TEST_DB"
-    rc=0
-    out=`$SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1` || rc=$?
-    if [ $rc -eq 0 ] ; then
-	echo "scriptindex didn't exit with non-zero return code on bad escaping"
-	failed=`expr $failed + 1`
-    elif printf '%s' "$out" \
-	| grep -q ":1:14: error: Bad escaping in quoted action argument" ; then
-	: # OK
-    else
-	echo "scriptindex didn't give expected error for bad escaping"
-	printf '%s\n' "badesc=$badesc" "got: $out"
-	failed=`expr $failed + 1`
-    fi
+    test_scriptindex_error "bad escaping '$badesc'" \
+      "$TEST_INDEXSCRIPT:1:14: error: Bad escaping in quoted action argument"
 done
 
 # Regression test that a closing " with junk after is flagged.
@@ -1575,14 +1542,8 @@ fi
 
 # Test we warn about useless actions.
 printf 'date : field parsedate=%%Y%%m%%d' > "$TEST_INDEXSCRIPT"
-rm -rf "$TEST_DB"
-if $SCRIPTINDEX "$TEST_DB" "$TEST_INDEXSCRIPT" < /dev/null 2>&1 \
-    | grep -q ":1:14: warning: Index action 'parsedate' has no effect" ; then
-    : # OK
-else
-    echo "scriptindex didn't give expected warning for useless 'parsedate'"
-    failed=`expr $failed + 1`
-fi
+test_scriptindex_warning "useless 'parsedate'" \
+  "$TEST_INDEXSCRIPT:1:14: warning: Index action 'parsedate' has no effect*"
 
 # Test scriptindex `gap` action inserts a termpos gap.
 printf 'text : index gap=5' > "$TEST_INDEXSCRIPT"
