git-tag-release: Retry GPG signing
This avoids having to perform the remaining steps in the script by
hand if you let GPG time out.

diff --git a/xapian-maintainer-tools/git-tag-release b/xapian-maintainer-tools/git-tag-release
--- a/xapian-maintainer-tools/git-tag-release
+++ b/xapian-maintainer-tools/git-tag-release
@@ -93,7 +93,8 @@ cd ..
 RESULT=`mktemp -d "RESULT-$version-XXXXXXXXXX"`
 echo "Signing tarballs"
 find "$DIR" -name "xapian-*-$version.tar.*"|while read f ; do
-    gpg --detach-sign --armour "$f"
+    # Retry signing until successful.
+    while ! gpg --detach-sign --armour "$f" ; do sleep 60 ; done
     mv "$f" "$f.asc" "$RESULT"
 done
 
