configure.ac,xapian-config.in: Some Linux distros have an unhelpful policy of not packaging .la files, and on Linux link_all_deplibs_CXX=no so we don't actually need to link in the dependency_libs.  So use the value of link_all_deplibs_CXX from configure to control whether we link against dependency_libs. xapian-config.in: Factor out common code into shell functions, and tidy up --help output. xapian-config.in: Re entry "Tue May 11 20:55:56 BST 2004": the (C) dates I mined from CVS included a BrightStation (C), but the few fragments of that version which survive are actually from glib-config (or one of the myriad of *-config scripts which look very like it), and are just standard Bourne shell idioms anyway.
git-svn-id: file:///home/xapian-svn/xapian/trunk@6565 6b2f1b92-a4f3-0310-943f-de3cbe41748b

diff --git a/xapian-core/xapian-config.in b/xapian-core/xapian-config.in
--- a/xapian-core/xapian-config.in
+++ b/xapian-core/xapian-config.in
@@ -1,7 +1,6 @@
-#! /bin/sh
+#!/bin/sh
 # @configure_input@
 #
-# Copyright (C) 1999,2000,2001 BrightStation PLC
 # Copyright (C) 2002,2003,2004,2005,2006 Olly Betts
 #
 # This program is free software; you can redistribute it and/or
@@ -19,40 +18,105 @@
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
 # USA
 
-prefix="@prefix@"
-exec_prefix="@exec_prefix@"
-libdir="@libdir@"
-includedir="@includedir@"
+# We require at least one argument.
+[ 0 != "$#" ] || show_usage 1 1>&2
 
-usage()
-{
+# Show usage information and exit with the specified exit status.
+show_usage() {
     cat <<EOF
-Usage: xapian-config [OPTION]...
+Usage: $0 [OPTION]...
 
 Options:
-  --libs	print library linking information
-  --ltlibs	print library linking information for linking with GNU libtool
-  --cxxflags	print preprocessor and compiler flags
-  --swigflags	print preprocessor flags for SWIG
-  --help	display this help and exit successfully
-  --version	output version information
+  --cxxflags   output all preprocessor and C++ compiler flags
+  --libs       output all linker flags
+  --ltlibs     output linker flags for linking using GNU libtool
+  --swigflags  output preprocessor flags for use with SWIG
+  --help       output this help and exit
+  --version    output version information and exit
 EOF
 
     exit $1
 }
 
-if test 0 = "$#"; then
-    usage 1
-fi
+# Cached value.  Note that this a return code, so 0 means uninstalled!
+is_uninstalled_cache=
 
-builddir="`echo $0|sed 's![^/]*$!!'`"
+# Check if this is an uninstalled xapian-config.
+is_uninstalled()
+{
+    if [ -z "$uninstalled_cache" ]; then
+	[ -n "$builddir" -a -f "${builddir}Makefile" ]
+	is_uninstalled_cache=$?
+    fi
+    return $is_uninstalled_cache
+}
+
+# Any extra ldflags needed.
+set_F_to_extra_ldflags() {
+    F=
+    [ -n "@ldflags@" ] && F="@ldflags@ "
+}
+
+# -L option required (if any).
+set_L_to_library_path() {
+    L=
+    [ /usr/lib != "@libdir" ] && L="-L@libdir@ "
+}
+
+# -I options for compiling against an uninstalled xapian.
+set_I_for_uninstalled() {
+    I=
+    # version.h is generated by configure, so we also need builddir
+    # in the include path if it's different to srcdir.
+    [ "@abs_srcdir@" != "@abs_builddir@" ] && I="-I@abs_builddir@/include "
+    I="$I-I@abs_srcdir@/include"
+}
+
+builddir=`echo $0|sed 's![^/]*$!!'`
 xo_lib_xapian=no
 
-while test 0 != "$#"; do
-    case "$1" in
+while arg=$1 && shift ; do
+    case $arg in
+    --help)
+	show_usage 0
+	;;
+
     --version)
 	echo "xapian @VERSION@"
 	exit 0
+	;;
+
+    --cxxflags)
+	if is_uninstalled ; then
+	    set_I_for_uninstalled
+	else
+	    # Adding -I/usr/include to CXXFLAGS causes problems with certain
+	    # versions of GCC on some platforms where GCC generates "fixed"
+	    # versions of vendor supplied include headers at install time.
+	    # Normally these are used instead of those in /usr/include, but if
+	    # you explicitly pass -I/usr/include you get the non-fixed
+	    # versions.  More recent GCC versions simply ignore -I/usr/include
+	    # but we want to support older versions too.
+	    case "@includedir@" in
+	    /usr/include|/usr/include/c++) I= ;;
+	    *) I="-I@includedir@" ;;
+	    esac
+	fi
+	cxxflags=
+	[ -n "@ANSI_CXXFLAGS@" ] && cxxflags="@ANSI_CXXFLAGS@ "
+	[ -n "@STLPORT_CXXFLAGS@" ] && cxxflags="${cxxflags}@STLPORT_CXXFLAGS@ "
+	echo "$cxxflags$I"
+	;;
+
+    --swigflags)
+	if is_uninstalled ; then
+	    # version.h is generated by configure, so we also need builddir
+	    # in the include path if it's different to srcdir.
+	    set_I_for_uninstalled
+	else
+	    I="-I@includedir@"
+	fi
+	echo "$I"
 	;;
 
     --from-xo-lib-xapian)
@@ -62,63 +126,17 @@ while test 0 != "$#"; do
 	xo_lib_xapian=yes
 	;;
 
-    --help)
-	usage 0
-	;;
-
-    --cxxflags)
-	inc=
-	# check if this is an uninstalled xapian-config
-	if test -n "$builddir" -a -f "${builddir}Makefile" ; then
-	    inc=
-	    # version.h is generated by configure, so we need builddir too
-	    test "@abs_srcdir@" != "@abs_builddir@" && inc="-I@abs_builddir@/include "
-	    inc="$inc-I@abs_srcdir@/include -I@abs_srcdir@/extra"
-	else
-	    # Adding -I/usr/include to CXXFLAGS causes problems with certain
-	    # versions of GCC on some platforms where GCC generates "fixed"
-	    # versions of vendor supplied include headers at install time.
-	    # Normally these are used instead of those in /usr/include, but if
-	    # you explicitly pass -I/usr/include you get the non-fixed
-	    # versions.  More recent GCC versions simply ignore -I/usr/include
-	    # but we want to support older versions too.
-	    case "$includedir" in
-	    /usr/include|/usr/include/c++) ;;
-	    *) inc="-I$includedir" ;;
-	    esac
-	fi
-	cxxflags=
-	test -n "@ANSI_CXXFLAGS@" && cxxflags="@ANSI_CXXFLAGS@ "
-	test -n "@STLPORT_CXXFLAGS@" && cxxflags="${cxxflags}@STLPORT_CXXFLAGS@ "
-	echo "${cxxflags}$inc"
-	;;
-
-    --swigflags)
-	inc=
-	# check if this is an uninstalled xapian-config
-	if test -n "$builddir" -a -f "${builddir}Makefile" ; then
-	    inc=
-	    # version.h is generated by configure, so we need builddir too
-	    test "@abs_srcdir@" != "@abs_builddir@" && inc="-I@abs_builddir@/include "
-	    inc="$inc-I@abs_srcdir@/include -I@abs_srcdir@/extra"
-	else
-	    inc="-I$includedir"
-	fi
-	echo "$inc"
-	;;
-
     --libs)
-	# check if this is an uninstalled xapian-config
-	if test -n "$builddir" -a -f "${builddir}Makefile" ; then
-	    if test no = "$xo_lib_xapian" ; then
+	if is_uninstalled ; then
+	    if [ no = "$xo_lib_xapian" ]; then
 		echo "$0: Use libtool and 'xapian-config --ltlibs'" 1>&2
 	    else
 		configure_ac='configure.in (or configure.ac)'
 		# If ac_top_srcdir isn't passed to us, we just end up looking
 		# in the current directory, which is a sensible fallback.
-		if test -r "${ac_top_srcdir}configure.ac" ; then
+		if [ -r "${ac_top_srcdir}configure.ac" ]; then
 		    configure_ac=configure.ac
-		elif test -r "${ac_top_srcdir}configure.in" ; then
+		elif [ -r "${ac_top_srcdir}configure.in" ]; then
 		    configure_ac=configure.in
 		fi
 		echo "$0: Add AC_PROG_LIBTOOL to your $configure_ac" 1>&2
@@ -126,49 +144,60 @@ while test 0 != "$#"; do
 	    echo "to link with an uninstalled libxapian." 1>&2
 	    exit 1
 	fi
-	F=
-	test -n "@ldflags@" && F="@ldflags@ "
-	L=
-	test /usr/lib != "$libdir" && L="-L$libdir "
+	set_F_to_extra_ldflags
+	set_L_to_library_path
 	D=
-	eval `grep ^dependency_libs= "$libdir/libxapian.la"`
-	# Replace "/path/to/libfoo.la" with "-L/path/to -lfoo" which doesn't
-	# take into account any dependency_libs which libfoo.la may pull in
-	# but the only .la that we're likely to see is libstdc++.la and it'll
-	# hopefully work there as any dependency libs will probably be pulled
-	# in by the compiler for us.  Recursively pulling in dependency_libs
-	# is probably too hard to do in sh - we'd need to reimplement
-	# xapian-config in C or C++.
-	dependency_libs=`echo " $dependency_libs "|sed 's![     ][      ]*!  !g;s! \(/[^ ]*\)/lib\([^ ]*\).la ! -L\1 -l\2 !g;s!  ! !g;s!^ !!;s! $!!'`
-	test -n "$dependency_libs" && D=" $dependency_libs"
+	# Only pull in dependency_libs if libtool would.
+	if [ no != "@link_all_deplibs_CXX@" ]; then
+	    eval `grep ^dependency_libs= "@libdir@/libxapian.la"`
+	    # Replace "/path/to/libfoo.la" with "-L/path/to -lfoo" which doesn't
+	    # take into account any dependency_libs which libfoo.la may pull in
+	    # but the only .la that we're likely to see is libstdc++.la and it'll
+	    # hopefully work there as any dependency libs will probably be pulled
+	    # in by the compiler for us.  Recursively pulling in dependency_libs
+	    # is probably too hard to do in sh - we'd need to reimplement
+	    # xapian-config in C or C++.
+	    dependency_libs=`echo " $dependency_libs "|sed 's![     ][      ]*!  !g;s! \(/[^ ]*\)/lib\([^ ]*\).la ! -L\1 -l\2 !g;s!  ! !g;s!^ !!;s! $!!'`
+	    [ -n "$dependency_libs" ] && D=" $dependency_libs"
+	fi
 	echo "$F$L-lxapian$D"
 	;;
 
     --ltlibs)
-	F=
-	test -n "@ldflags@" && F="@ldflags@ "
-	# check if this is an uninstalled xapian-config
-	if test -n "$builddir" -a -f "${builddir}Makefile" ; then
-	    # don't check if libxapian.la exists yet - it won't unless
+	set_F_to_extra_ldflags
+	if is_uninstalled ; then
+	    # Don't check if libxapian.la exists yet - it won't unless
 	    # the xapian-core tree has been built!
-	    echo "$F${builddir}libxapian.la"
-	    exit 0
+	    [ ./ != "$builddir" ] && F="$F$builddir"
+	    echo "${F}libxapian.la"
+	    continue
 	fi
 
-	if test -f "$libdir/libxapian.la"; then
-	    echo "$F$libdir/libxapian.la"
-	    exit 0
+	if [ -f "@libdir@/libxapian.la" ]; then
+	    echo "${F}@libdir@/libxapian.la"
+	    continue
 	fi
 
-	echo "$0: Can't find libxapian.la to link against." 1>&2
-	exit 1
+	# If libtool wouldn't pull in dependency_libs, we can cope with letting
+	# libtool link without the .la file (some Linux distros have an
+	# unhelpful policy of not packaging .la files, and on Linux
+	# link_all_deplibs_CXX=no).
+	if [ no != "@link_all_deplibs_CXX@" ]; then
+	    echo "$0: Can't find libxapian.la to link against." 1>&2
+	    exit 1
+	fi
+	set_L_to_library_path
+	echo "$F$L-lxapian"
+	;;
+
+    -*)
+	echo "$0: Unrecognized option: $arg" 1>&2
+	show_usage 1 1>&2
 	;;
 
     *)
-	usage 1 1>&2
-	exit 1
+	show_usage 1 1>&2
 	;;
     esac
-    shift
 done
 exit 0
