Fixed wrong script name in error message
git-svn-id: file:///home/xapian-svn/xapian/trunk@6856 6b2f1b92-a4f3-0310-943f-de3cbe41748b

diff --git a/xapian-maintainer-tools/debian/makesources b/xapian-maintainer-tools/debian/makesources
--- a/xapian-maintainer-tools/debian/makesources
+++ b/xapian-maintainer-tools/debian/makesources
@@ -64,7 +64,7 @@ fi
 DOWNLOAD_BASE="http://www.oligarchy.co.uk/xapian/"
 
 ## BEGIN PROCESSING ##
-trap "echo \"makedebs failed\"" EXIT
+trap "echo \"makesources failed\"" EXIT
 
 # Get the component specified by the user.
 if [ -n "$1" ] ; then
