Fix failing multi_glass_remoteprog_glass tests on x86
When the tests are run under valgrind, remote servers should be run
using the runsrv wrapper script, but this wasn't happening for
remote servers in multi-databases - now it is.

Also, previously runsrv only used valgrind for the remote for an x86
build that didn't use SSE, but it seems there are x87 instructions in
libc that are affected by valgrind not providing excess precision, so do
this for x86 builds which use SSE too.

Together these changes fix failures of topercent2, xor2, tradweight1
under backend multi_glass_remoteprog_glass on x86.

diff --git a/xapian-core/tests/runsrv.in b/xapian-core/tests/runsrv.in
--- a/xapian-core/tests/runsrv.in
+++ b/xapian-core/tests/runsrv.in
@@ -6,14 +6,12 @@
 #
 # We use this wrapper script so that we can run the remote servers under
 # valgrind if required.  This is needed on x86 when the testsuite is using
-# valgrind and we were told to build the library without SSE instructions.
-# The issue is that valgrind's emulation of excess FP precision isn't exact,
-# which causes test failures.
+# valgrind to avoid issues due to valgrind not supporting x87 excess precision.
 #
 # We don't actually need valgrind's checking here, so we use "--tool=none"
 # which is much quicker than using valgrind's default memcheck tool.
 #
-# Copyright (C) 2003,2004,2007,2009,2012 Olly Betts
+# Copyright (C) 2003,2004,2007,2009,2012,2019 Olly Betts
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License as
@@ -31,12 +29,21 @@
 # USA
 
 if test 0 = "$#"; then
-   echo "syntax: $0 <remote backend server program> <arguments>"
-   exit 1
+  echo "syntax: $0 <remote backend server program> <arguments>"
+  exit 1
 fi
 
-# Just run the server if valgrind's imperfect x87 emulation isn't an issue.
-[ "x@FP_EXCESS_PRECISION@" = "xno" ] && exec "$@"
+# We used to only do this on x86 when also building the library without SSE
+# instructions (which works around valgrind implementing 80 bit FP using
+# 64 bit FP instructions), but the addition of multi_glass_remoteprog_glass
+# resulted in 3 failing testcases under valgrind on x86 even when built with
+# -msse2 - presumably there's some libc function using x87 FP.
+case "@host_cpu@" in
+  i*86) ;;
+  *)
+    # Just run the server directly for other architectures.
+    exec "$@" ;;
+esac
 
 # Set srcdir if it isn't already.
 : ${srcdir="@srcdir@"}
