CI: Add job on macOS 27

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1260,6 +1260,112 @@ jobs:
         path: |
           **/*.log
 
+  macos-27:
+    runs-on: 'xcode-27'
+    needs: makedist
+    steps:
+    - name: Remove unwanted taps
+      run: |
+        # Remove taps we don't use, which avoids warnings about untrusted taps
+        # and means we're testing a more standard homebrew setup.
+        brew untap --force aws/tap hashicorp/tap azure/bicep || true
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1.2.21
+      with:
+        key: ${{ github.job }}
+    - name: Fetch distribution
+      uses: actions/download-artifact@v8
+      with:
+        name: artifact
+    - name: Unpack distribution
+      run: |
+        pushd xapian-core
+        tar --strip-components=1 -xf xapian-core-*.tar.xz
+        popd
+        pushd xapian-omega
+        tar --strip-components=1 -xf xapian-omega-*.tar.xz
+        popd
+        pushd xapian-bindings
+        tar --strip-components=1 -xf xapian-bindings-*.tar.xz
+        popd
+        pushd xapian-letor
+        tar --strip-components=1 -xf xapian-letor-*.tar.xz
+        popd
+    - name: Install package dependencies
+      run: |
+        brew update
+        brew install -q \
+            gmime \
+            icu4c \
+            libabw \
+            libarchive \
+            libcdr \
+            libetonyek \
+            libextractor \
+            libiconv \
+            libmagic \
+            libmwaw \
+            libspectre \
+            lua \
+            pcre2 \
+            php \
+            pkgconfig \
+            poppler \
+            pygments \
+            python \
+            tcl-tk \
+            tesseract
+        pip3 install --user --break-system-packages Sphinx
+        # mono-mdk: "make check" fails on arm64 macos-27 (but worked on
+        # x86_64 macos-12 and macos-13).  Last checked 2026-09-20.
+        #
+        # libeatmydata doesn't currently actually do anything on macOS:
+        # https://github.com/stewartsmith/libeatmydata/issues/34
+        # It's also started failing to even run in homebrew so don't install
+        # for now.
+    - name: configure
+      run: |
+        export CC='ccache gcc'
+        export CXX='ccache g++'
+        export PKG_CONFIG_PATH="$(brew --prefix icu4c)/lib/pkgconfig"
+        pushd xapian-core
+        ./configure --enable-werror --prefix='${{ runner.temp }}/XapianInstall'
+        export XAPIAN_CONFIG=$PWD/xapian-config
+        popd
+        pushd xapian-omega
+        ./configure --enable-werror --with-libiconv-prefix="$(brew --prefix libiconv)" CPPFLAGS="-I${HOMEBREW_PREFIX:-/usr/local}/include"
+        popd
+        pushd xapian-bindings
+        ./configure --enable-werror --with-java --with-lua --with-perl --with-php --with-python3 --with-ruby --with-tcl
+        popd
+        pushd xapian-letor
+        ./configure --enable-werror
+        popd
+    - name: make
+      run: |
+        make -j3 -C xapian-core
+        make -j3 -C xapian-core install
+        make -j3 -C xapian-omega
+        make -j3 -C xapian-bindings
+        make -j3 -C xapian-letor
+    - name: Run tests
+      run: |
+        export LIBEXTRACTOR_PREFIX=${HOMEBREW_PREFIX:-/usr/local}/lib/libextractor
+        export AUTOMATED_TESTING=1
+        export VERBOSE=1
+        make -j3 -C xapian-core check
+        make -j3 -C xapian-omega check
+        make -j3 -C xapian-bindings check
+        make -j3 -C xapian-letor check
+    - name: Save log files
+      if: ${{ failure() }}
+      uses: actions/upload-artifact@v7
+      with:
+        name: logs-${{ github.job }}-${{ github.sha }}
+        overwrite: true
+        path: |
+          **/*.log
+
   macos-26:
     runs-on: 'macos-26'
     needs: makedist
