[ci] Add FreeBSD job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1590,6 +1590,64 @@ jobs:
         #make -j2 -C xapian-bindings check
         make -j2 -C xapian-letor check
 
+  freebsd:
+    runs-on: 'macos-12'
+    needs: makedist
+    steps:
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: freebsd
+    - name: Fetch distribution
+      uses: actions/download-artifact@v3
+    - name: Unpack distribution
+      run: |
+        mv artifact/* .
+        rmdir artifact
+        # Do actual unpacking on freebsd, mostly to help reduce the size of the
+        # rsync output in the logs.
+    - name: Run in FreeBSD VM
+      uses: vmactions/freebsd-vm@v0
+      with:
+        usesh: true
+        prepare: |
+          set -e
+          pkg install -y bash ccache perl5 pcre2
+          ccache --set-config=cache_dir='/Users/runner/work/xapian/xapian/.ccache'
+          ccache --set-config=max_size='500M'
+          ccache --set-config=compression=true
+        run: |
+          set -e
+          export CC='ccache cc'
+          export CXX='ccache c++'
+          cd xapian-core
+          tar --strip-components=1 -xf xapian-core-*.tar.xz
+          ./configure --enable-werror
+          export XAPIAN_CONFIG=$PWD/xapian-config
+          cd ..
+          cd xapian-applications/omega
+          tar --strip-components=1 -xf xapian-omega-*.tar.xz
+          ./configure --enable-werror
+          cd ../..
+          # cd xapian-bindings
+          # tar --strip-components=1 -xf xapian-bindings-*.tar.xz
+          # cd ..
+          cd xapian-letor
+          tar --strip-components=1 -xf xapian-letor-*.tar.xz
+          ./configure --enable-werror
+          cd ..
+          # Everything gets run in on script so use V=0 to reduce the size of
+          # the log, but re-run without V=0 on failure to show the compiler
+          # command line.
+          make -j2 -C xapian-core V=0 || make -C xapian-core
+          make -j2 -C xapian-applications/omega V=0 || make -C xapian-core
+          make -j2 -C xapian-letor V=0 || make -C xapian-letor
+          export AUTOMATED_TESTING=1
+          export VERBOSE=1
+          make -j2 -C xapian-core check V=0
+          make -j2 -C xapian-applications/omega check V=0
+          make -j2 -C xapian-letor check V=0
+
   checkpatch:
     name: 'Automated run of xapian-check-patch'
     runs-on: 'ubuntu-latest'
