[ci] Add job to test with clang 6
This seems to be the oldest version that's easily available.

(cherry picked from commit f11992bf64a293903e1f904ee83bdac2bbb4e3f7)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -149,6 +149,50 @@ jobs:
       # if that input is empty.
       run: git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
 
+  # Test with the oldest clang version we easily can.
+  clang6:
+    runs-on: 'ubuntu-18.04'
+    steps:
+    - name: Check out repository code
+      uses: actions/checkout@v2
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: clang6
+    - name: Install package dependencies
+      run: |
+        env
+        sudo apt-get update
+        sudo apt-get install \
+            clang \
+            libc++-dev
+        sudo apt-get install \
+            doxygen \
+            graphviz \
+            help2man \
+            python3-docutils \
+            pngcrush \
+            python3-sphinx \
+            uuid-dev \
+            libpcre2-dev \
+            libmagic-dev \
+            python3-dev \
+            tcl \
+            tcl-dev
+    - name: bootstrap source tree
+      run: ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
+    - name: configure
+      # Build with the llvm c++ library to catch more portability issues.
+      run: ./configure CC='ccache clang' CXX='ccache clang++ -stdlib=libc++' --with-python3 --with-tcl
+    - name: make
+      run: make -j2
+    - name: Run tests
+      run: make -j2 check VERBOSE=1 AUTOMATED_TESTING=1
+    - name: Check generated files are in .gitignore
+      # grep '^' passes through all input while giving a non-zero exit status
+      # if that input is empty.
+      run: git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
+
   # GCC 4.7 is the oldest GCC we aim to support for 1.4.x, but the oldest we can
   # easily build with in github actions is 4.8.  There's no package of GCC 4.8
   # in Ubuntu 20.04 so we have to run this on 18.04 (also useful to test
